import type { Card, DeckGroup } from './types';

export const flashcards: Card[] = [
  { id: 1, front: "お供しいとこ", back: "お — Qayerga borish kerak / tail (of an animal), cauda" },
  { id: 2, front: "お卵", back: "おとしたまご — tuxum / poached egg" },
  { id: 3, front: "お口", back: "おおぐち — og'iz / big mouth, mouth opened wide" },
  { id: 4, front: "お名前", back: "おなまえ — nomi / name" },
  { id: 5, front: "お問", back: "おといあわせばんごう — Savol / reference number, order number, tracking number" },
  { id: 6, front: "お忙しいとこ", back: "と — Men bandman. / door (esp. Japanese-style)" },
  { id: 7, front: "お手数をおかけ", back: "おてすうをおかけいたします — noqulayliklar uchun uzr so'raymiz / to be a burden, to make trouble for someone" },
  { id: 8, front: "お皿", back: "おさら — plastinka / plate, dish" },
  { id: 9, front: "お金など", back: "おかね — pul va boshqalar. / money" },
  { id: 10, front: "お願いがあ", back: "おねがい — Bir iltimosim bor / request, favour (to ask), wish" },
  { id: 11, front: "お願いがある", back: "おねがい — Bir iltimosim bor / request, favour (to ask), wish" },
  { id: 12, front: "ご了承ください", back: "ごりょうしょうください — shu esta tutilsinki / please be aware (that ...), please note (that ...), please understand (that ...)" },
  { id: 13, front: "ご型", back: "ごぶんけい — mog'or / the five basic sentence structures of English (SV, SVC, SVO, SVOO, SVOC)" },
  { id: 14, front: "一です", back: "です — Bu bitta / be, is" },
  { id: 15, front: "一位", back: "いちい — Birinchi o'rin / first place, first rank" },
  { id: 16, front: "一度恥", back: "いちど — bir marta uyat / once, one time, on one occasion" },
  { id: 17, front: "一段", back: "いちだん — Bir bosqich / even more, still more, much more, further" },
  { id: 18, front: "一等", back: "いっとう — birinchi sinf / first class, first rank, first grade, first place, first prize" },
  { id: 19, front: "一緒に行った", back: "いっしょに — birga ketdi / together (with)" },
  { id: 20, front: "一首歌", back: "Bitta she'r / One poem" },
  { id: 21, front: "上司にきずら", back: "じょうし — Rahbar bilan muammo / A problem with the boss" },
  { id: 22, front: "上型", back: "Yuqori mog'or / Upper mold" },
  { id: 23, front: "下取り", back: "したどり — Savdo / Trade-in" },
  { id: 24, front: "下取りして", back: "したどり — Savdo qiling / Trade it in" },
  { id: 25, front: "不成体統", back: "とういつ — amorf tana / amorphous body" },
  { id: 26, front: "世紀", back: "せいき — asr / century" },
  { id: 27, front: "世紀に完成した", back: "せいき — asrda yakunlangan / completed in the century" },
  { id: 28, front: "丘口", back: "Okaguchi / Okaguchi" },
  { id: 29, front: "両子", back: "Ikkala bola ham / Both children" },
  { id: 30, front: "両目", back: "りょうめ — ikkala ko'z / both eyes" },
  { id: 31, front: "並み性", back: "o'rtacha sifat / average quality" },
  { id: 32, front: "並んでいる", back: "ならんで — saf tortdi / lined up" },
  { id: 33, front: "中の仏像", back: "ちゅう — Ichkarida Budda haykali / Buddha statue inside" },
  { id: 34, front: "中の企像", back: "ちゅう — ichkarida rejalashtirish / plan inside" },
  { id: 35, front: "中三口", back: "ちゅう — O'rta uchta og'iz / Middle three mouths" },
  { id: 36, front: "中央改札", back: "ちゅうおう — markaziy chipta darvozasi / central ticket gate" },
  { id: 37, front: "乍一看", back: "みる — Qarang / Take a look" },
  { id: 38, front: "予定がきっし", back: "よてい — Mening jadvalim mukammal / My schedule is perfect" },
  { id: 39, front: "事務", back: "じむ — Ofis ishi / Office work" },
  { id: 40, front: "事務職", back: "じむしょく — Ofis ishi / Office job" },
  { id: 41, front: "事実だけあっ", back: "じじつ — Faqat faktlar / Just the facts" },
  { id: 42, front: "事実だとすれ", back: "じじつ — Faraz qilaylik, bu haqiqat / Let's assume it's a fact" },
  { id: 43, front: "事実どおり", back: "faktlarga ko'ra / as per the facts" },
  { id: 44, front: "事実のまま", back: "じじつ — haqiqat bo'lib qolsin / remain true" },
  { id: 45, front: "二部こる", back: "こる — 2-qism yomon / Part 2 is bad" },
  { id: 46, front: "井目", back: "せいもく — Ime / Ime" },
  { id: 47, front: "亡くなった", back: "なくなる — vafot etdi / passed away" },
  { id: 48, front: "人の意見を尊重し", back: "ひと — odamlarning fikrini hurmat qiling / respect people's opinions" },
  { id: 49, front: "人の魚を救う", back: "ひと — odamlarning baliqlarini saqlang / save people's fish" },
  { id: 50, front: "今日はしつど", back: "きょう — Bugun men buni qilaman / Today I will do it" },
  { id: 51, front: "今日豆", back: "きょう — Bugungi loviya / Today's beans" },
  { id: 52, front: "今納得がいか", back: "が — Endi qoniqdingizmi? / Are you satisfied now?" },
  { id: 53, front: "今要", back: "いま — Kaname hozir / Kaname now" },
  { id: 54, front: "仕事", back: "しごと — ish / work" },
  { id: 55, front: "仕事がすごく", back: "しごと — Mening juda ko'p ishlarim bor / I have a lot of work to do" },
  { id: 56, front: "仕事が私", back: "しごと — ish men / work is me" },
  { id: 57, front: "仕事ぶり", back: "しごとぶり — Ish samaradorligi / Work performance" },
  { id: 58, front: "他的漫画", back: "まんが — boshqa manga / other manga" },
  { id: 59, front: "以上", back: "いじょう — Hammasi shu / That's all" },
  { id: 60, front: "仮名", back: "かな — Kana / Kana" },
  { id: 61, front: "仮店", back: "かりてんぽ — Vaqtinchalik do'kon / Temporary store" },
  { id: 62, front: "仮認", back: "かり — vaqtinchalik tan olish / provisional recognition" },
  { id: 63, front: "企業が増えてきた", back: "きぎょう — Kompaniyalar soni ortdi / The number of companies has increased" },
  { id: 64, front: "企画", back: "きかく — Rejalashtirish / Planning" },
  { id: 65, front: "会対", back: "かい — uchrashuv / meeting" },
  { id: 66, front: "会社", back: "かいしゃ — kompaniya / company" },
  { id: 67, front: "会社を辞めたい", back: "かいしゃ — Men ishimni tashlamoqchiman / I want to quit my job" },
  { id: 68, front: "伯父の家には本", back: "おじ — Amakimning uyida kitoblar bor. / There are books at my uncle's house." },
  { id: 69, front: "估分", back: "bo'linish / division" },
  { id: 70, front: "但是", back: "ただ — Biroq, shunday / However, it is" },
  { id: 71, front: "低下する", back: "ていか — pasayish / decline" },
  { id: 72, front: "何と", back: "なんと — Nima / What" },
  { id: 73, front: "何とかなら", back: "なんとか — Agar bu qandaydir tarzda mumkin bo'lsa / If it's somehow possible" },
  { id: 74, front: "作った料理", back: "つくる — siz qilgan taom / the dish you made" },
  { id: 75, front: "修理する", back: "しゅうりするけんり — ta'mirlash / repair" },
  { id: 76, front: "修理するくら", back: "しゅうり — Qancha ta'mirlash kerak / How much to repair" },
  { id: 77, front: "個おせしい", back: "こ — Bir parcha / One piece" },
  { id: 78, front: "値引き", back: "ねびき — chegirma / discount" },
  { id: 79, front: "値引きする", back: "ねびき — chegirma / discount" },
  { id: 80, front: "値打ち", back: "ねうち — bunga arziydi / worth it" },
  { id: 81, front: "偏差", back: "へんさ — og'ish / deviation" },
  { id: 82, front: "健康態は鳥好です", back: "けんこう — Qushning salomatligi yaxshi. / The bird is in good health." },
  { id: 83, front: "健康状態", back: "けんこうじょうたい — salomatlik holati / health condition" },
  { id: 84, front: "偶然", back: "ぐうぜん — tasodif / coincidence" },
  { id: 85, front: "催す", back: "もよおす — mezbon / host" },
  { id: 86, front: "像", back: "ぞう — haykal / statue" },
  { id: 87, front: "兄または姉", back: "あに — uka yoki opa / brother or sister" },
  { id: 88, front: "先にしまし", back: "さき — Men birinchi bo'lib qilaman / I'll do it first" },
  { id: 89, front: "先程", back: "さきほど — Avvalroq / Earlier" },
  { id: 90, front: "先輩", back: "せんぱい — katta / senior" },
  { id: 91, front: "光熱費", back: "こうねつひ — Kommunal xarajatlar / Utility expenses" },
  { id: 92, front: "入れ", back: "いれ — Uni qo'ying / Put it in" },
  { id: 93, front: "入場", back: "にゅうじょう — Qabul / Admission" },
  { id: 94, front: "入学料", back: "いり — Kirish to'lovi / Admission fee" },
  { id: 95, front: "入学費", back: "Kirish to'lovi / Admission fee" },
  { id: 96, front: "入学賃", back: "Kirish to'lovi / Admission fee" },
  { id: 97, front: "入学金", back: "にゅうがくきん — Kirish to'lovi / Admission fee" },
  { id: 98, front: "八場", back: "Yaba / Yaba" },
  { id: 99, front: "公感", back: "ommaviy tuyg'u / public feeling" },
  { id: 100, front: "内臓", back: "ないぞう — ichki organlar / internal organs" },
  { id: 101, front: "内臓の働きがよく", back: "ないぞう — Ichki organlar yaxshi ishlaydi / Internal organs work well" },
  { id: 102, front: "出して", back: "だしてくれる — Uni olib tashlang / Take it out" },
  { id: 103, front: "出合利目", back: "であい — Deai foyda / Deai profit" },
  { id: 104, front: "出張するんだ", back: "しゅっちょう — Men xizmat safariga ketyapman / I'm going on a business trip" },
  { id: 105, front: "出来", back: "でき — Bajarildi / Done" },
  { id: 106, front: "分しかない", back: "ぶん — Faqat daqiqalar bor / There are only minutes" },
  { id: 107, front: "分別", back: "ふんべつ — saralash / sorting" },
  { id: 108, front: "分別に悩まされて", back: "ふんべつ — tuyg'u bilan bezovta / troubled by sense" },
  { id: 109, front: "別入口", back: "べつ — Alohida kirish / Separate entrance" },
  { id: 110, front: "削減できた", back: "さくげん — kamaytirishga muvaffaq bo'ldi / was able to reduce" },
  { id: 111, front: "助かってい", back: "たすかる — Men najot topdim / I'm saved" },
  { id: 112, front: "動画", back: "どうが — Video / Video" },
  { id: 113, front: "化粧水", back: "けしょうすい — loson / lotion" },
  { id: 114, front: "午前中はこうぎ", back: "ごぜんちゅう — Kogi ertalab / Kogi in the morning" },
  { id: 115, front: "午後", back: "ごご — Peshindan keyin / Afternoon" },
  { id: 116, front: "午煎由は講義", back: "ひる — Peshindan keyin ma'ruza / Afternoon is a lecture" },
  { id: 117, front: "単独", back: "たんどく — Yolg'iz / Alone" },
  { id: 118, front: "単純な手続き", back: "たんじゅん — oddiy protsedura / simple procedure" },
  { id: 119, front: "博土", back: "Xiroto / Hiroto" },
  { id: 120, front: "博士はすばら", back: "はかせ — Doktor ajoyib / Doctor is amazing" },
  { id: 121, front: "友生争", back: "do'stona to'qnashuv / friendly conflict" },
  { id: 122, front: "友達", back: "ともだち — do'stlar / friends" },
  { id: 123, front: "双ふた", back: "そう — egizak qopqoqlar / twin lids" },
  { id: 124, front: "双子", back: "ふたご — egizaklar / twins" },
  { id: 125, front: "収来", back: "しゅうにゅう — o'rim-yig'im / harvest" },
  { id: 126, front: "叔母", back: "おば — xola / aunt" },
  { id: 127, front: "取り上げた", back: "とりあげる — oldi / picked up" },
  { id: 128, front: "取り上げる", back: "とりあげる — olish / take up" },
  { id: 129, front: "取り入れた", back: "とりいれる — Kiritilgan / Incorporated" },
  { id: 130, front: "取り入れたこと", back: "とりいれる — Men olgan narsam / What I took in" },
  { id: 131, front: "取り入れる", back: "とりいれる — kiritish / incorporate" },
  { id: 132, front: "取り戻す", back: "とりもどす — qaytarib olish / take back" },
  { id: 133, front: "取り組む", back: "とりくむ — hal qilish / tackle" },
  { id: 134, front: "取り組んだ", back: "とりくむ — ustida ishlagan / worked on" },
  { id: 135, front: "取り込む", back: "とりこむ — qabul qilish / take in" },
  { id: 136, front: "取り込んだ", back: "とりこむ — Kiritilgan / Incorporated" },
  { id: 137, front: "受けられ", back: "うける — qabul qilingan / accepted" },
  { id: 138, front: "受け入れるべき", back: "うけいれる — qabul qilinishi kerak / should be accepted" },
  { id: 139, front: "受够了", back: "りょう — Qabul qilish tugallandi / Acceptance completed" },
  { id: 140, front: "古い車", back: "ふるい — eski mashina / old car" },
  { id: 141, front: "召开", back: "Ochilish / Opening" },
  { id: 142, front: "可是", back: "か — Mumkin / Possible" },
  { id: 143, front: "可能性は低い", back: "かのうせい — dargumon / unlikely" },
  { id: 144, front: "台湾からきま", back: "たいわん — Tayvan Karakima / Taiwan Karakima" },
  { id: 145, front: "号る", back: "ごうする — masala / issue" },
  { id: 146, front: "吃葯也没用", back: "チー — língíní / 吃萯也用" },
  { id: 147, front: "合のやるこ", back: "ごう — Go-no-Yaruko / Go-no-Yaruko" },
  { id: 148, front: "吉義", back: "Yoshiyoshi / Yoshiyoshi" },
  { id: 149, front: "同じ失敗はしなく", back: "おなじ — Xuddi shunday xatoga yo'l qo'ymang / Don't make the same mistake" },
  { id: 150, front: "同情", back: "どうじょう — hamdardlik / sympathy" },
  { id: 151, front: "同様", back: "どうよう — o'xshash / similar" },
  { id: 152, front: "向往", back: "むこう — Ketish va qaytish / Going to and from" },
  { id: 153, front: "君ならでき", back: "きみ — Siz qila olasiz / You can do it" },
  { id: 154, front: "君はもっ", back: "きみ — Siz ham / You are too" },
  { id: 155, front: "呼呆", back: "こきゅう — xirillash / hoarseness" },
  { id: 156, front: "哲る", back: "てつ — o'ylab ko'ring / think" },
  { id: 157, front: "問題ができる", back: "もんだい — muammolarga olib kelishi mumkin / can cause problems" },
  { id: 158, front: "喜ぶ", back: "よろこぶ — quvonmoq / rejoice" },
  { id: 159, front: "因此", back: "もと — Inko / Inko" },
  { id: 160, front: "因比", back: "nisbat / ratio" },
  { id: 161, front: "困るよ", back: "こまる — Men muammoga duch keldim / I'm in trouble" },
  { id: 162, front: "国に帰ること", back: "くに — o'z mamlakatiga qaytish / to return to one's country" },
  { id: 163, front: "国頭が痛かった", back: "Kunining boshi og'riyapti / Kuni's head hurt" },
  { id: 164, front: "地域", back: "ちいき — mintaqa / region" },
  { id: 165, front: "地面を掘ったら", back: "じめん — Agar siz yer qazsangiz / If you dig the ground" },
  { id: 166, front: "地面を撮ったら", back: "じめん — Agar siz yerni suratga olsangiz / If you take a picture of the ground" },
  { id: 167, front: "塔", back: "とう — minora / tower" },
  { id: 168, front: "塗りたて", back: "ぬりたて — Yangi bo'yalgan / Freshly painted" },
  { id: 169, front: "塾付", back: "Cram maktabi bilan / With cram school" },
  { id: 170, front: "塾談", back: "Maktab suhbati / School talk" },
  { id: 171, front: "壁りたて", back: "かべ — yangi qurilgan devor / freshly built wall" },
  { id: 172, front: "壱書する", back: "いち — bitta xat yozing / write one letter" },
  { id: 173, front: "変わってい", back: "かわっている — Bu boshqacha / It's different" },
  { id: 174, front: "夏する", back: "なつ — yoz / summer" },
  { id: 175, front: "夏志", back: "なつ — Natsushi / Natsushi" },
  { id: 176, front: "夏様", back: "なつ — Yoz / Summer" },
  { id: 177, front: "多台", back: "た — Ko'p birlik / Multiple units" },
  { id: 178, front: "多銭修逐不如", back: "たせん — Ko'p pul bunga loyiq emas / A lot of money is not worth it" },
  { id: 179, front: "夢敵する", back: "ゆめ — orzu raqib / dream rival" },
  { id: 180, front: "大会は寒かった", back: "たいかい — Turnir sovuq edi / The tournament was cold" },
  { id: 181, front: "大変だった", back: "たいへん — Bu qiyin edi / It was difficult" },
  { id: 182, front: "大幅度削減了表", back: "さくげん — Muhim qisqartirishni yakunlash jadvali / Significant reduction completion table" },
  { id: 183, front: "天然", back: "てんねん — tabiiy / natural" },
  { id: 184, front: "失度", back: "qo'pol xato / blunder" },
  { id: 185, front: "失礼だとされ", back: "しつれい — qo'pol deb hisoblanadi / considered rude" },
  { id: 186, front: "好で行かない", back: "こう — Men ketishni xohlamayman / I don't want to go" },
  { id: 187, front: "嫌われてい", back: "きらう — nafratlangan / hated" },
  { id: 188, front: "子のどちら", back: "こ — qaysi bola / which child" },
  { id: 189, front: "学費", back: "がくひ — O'qish to'lovi / Tuition fee" },
  { id: 190, front: "安慰", back: "あんい — qulaylik / comfort" },
  { id: 191, front: "安非", back: "やす — Anhi / Anhi" },
  { id: 192, front: "定義", back: "ていぎ — ta'rifi / definition" },
  { id: 193, front: "実費", back: "じっぴ — haqiqiy xarajat / actual cost" },
  { id: 194, front: "客感", back: "mijoz hissi / customer feeling" },
  { id: 195, front: "室度", back: "xona darajasi / room degree" },
  { id: 196, front: "害着", back: "Zararli kiyimlar / Harmful clothes" },
  { id: 197, front: "家にいたほ", back: "いえ — Men uyda edim / I was at home" },
  { id: 198, front: "家にこもる", back: "いえ — uyda qoling / stay at home" },
  { id: 199, front: "家事", back: "かじ — uy ishlari / housework" },
  { id: 200, front: "容する", back: "よういにする — chidash / tolerate" },
  { id: 201, front: "容量を早", back: "ようりょう — qobiliyatini tezlashtirish / speed up capacity" },
  { id: 202, front: "富むとみ", back: "とむ — Tomi Tomi / Tomi Tomi" },
  { id: 203, front: "富子", back: "Tomiko / Tomiko" },
  { id: 204, front: "少し横", back: "すこし — bir oz yon tomonga / a little sideways" },
  { id: 205, front: "就想起去世了的母", back: "そうき — O'tgan hayotimdan keyin yodimga kelgan onam / My mother who came to mind after my past life" },
  { id: 206, front: "就没", back: "tug'ilish va o'lim / birth and death" },
  { id: 207, front: "居眠り", back: "いねむり — Uyqusizlik / Dozing off" },
  { id: 208, front: "居間", back: "いま — yashash xonasi / living room" },
  { id: 209, front: "岡不出", back: "おか — Okabude / Okabude" },
  { id: 210, front: "岩中", back: "Ivanaka / Iwanaka" },
  { id: 211, front: "岩然", back: "いわ — Ivazen / Iwazen" },
  { id: 212, front: "川品", back: "Kavashina / Kawashina" },
  { id: 213, front: "工量", back: "harakat / effort" },
  { id: 214, front: "巻熱費が本幅", back: "が — Isitish narxi asosiy diapazondir. / The heating cost is the main range." },
  { id: 215, front: "帯来", back: "Obirai / Obirai" },
  { id: 216, front: "帰ること", back: "かえる — uyga borish / to go home" },
  { id: 217, front: "平らなとこ", back: "たいら — tekis joy / flat place" },
  { id: 218, front: "平厉地提醒你的", back: "ひら — Tekisliklardan uyg'onish / Awakening from the plains" },
  { id: 219, front: "平均", back: "へいきん — o'rtacha / average" },
  { id: 220, front: "平均的な数値", back: "へいきんてき — o'rtacha raqam / average number" },
  { id: 221, front: "平約", back: "ひら — tinchlik shartnomasi / peace agreement" },
  { id: 222, front: "年代", back: "ねんだい — davr / era" },
  { id: 223, front: "年数", back: "ねんすう — yillar / years" },
  { id: 224, front: "年月", back: "としつき — yil va oy / year and month" },
  { id: 225, front: "年齢は何歳です", back: "ねんれい — necha yoshdasiz / how old are you" },
  { id: 226, front: "床について", back: "ゆか — Zamin haqida / About the floor" },
  { id: 227, front: "店の拡張工事", back: "みせ — Do'konni kengaytirish qurilishi / Store expansion construction" },
  { id: 228, front: "店の熱器工事", back: "みせ — Do'kon isitish uskunalari qurilishi / Store heating equipment construction" },
  { id: 229, front: "度の割合", back: "たび — daraja foizi / degree percentage" },
  { id: 230, front: "引口", back: "ひきぐち — eshikni yopish / closing door" },
  { id: 231, front: "弥傲", back: "いや — Mening takabburligim / My arrogance" },
  { id: 232, front: "強調を蒸す", back: "きょうちょう — urg'uni bug'lang / steam the emphasis" },
  { id: 233, front: "当に必要なこと", back: "まさに — haqiqatan ham kerak bo'lgan narsa / what is really necessary" },
  { id: 234, front: "当口", back: "はた — Navbatda / On duty" },
  { id: 235, front: "当止如此", back: "はた — Bu erda to'xtash uchun / To stop here" },
  { id: 236, front: "当沢工あて", back: "Tozawa Tech kompaniyasiga murojaat qilgan. / Addressed to Tozawa Tech." },
  { id: 237, front: "当然だ", back: "とうぜん — Albatta / Of course" },
  { id: 238, front: "当計", back: "はた — Joriy byudjet / Current budget" },
  { id: 239, front: "彼が会社", back: "かれ — u kompaniya / he is the company" },
  { id: 240, front: "彼ぐらい", back: "かれ — U haqida / About him" },
  { id: 241, front: "彼の作品は面白い", back: "あの — uning ishi qiziq / his work is interesting" },
  { id: 242, front: "彼の漫画", back: "あの — uning mangasi / his manga" },
  { id: 243, front: "彼女", back: "かのじょ — u / she" },
  { id: 244, front: "彼女は美人だ", back: "かのじょ — u go'zal / she is beautiful" },
  { id: 245, front: "従って", back: "したがって — Shuning uchun / Therefore" },
  { id: 246, front: "得なく", back: "える — Foydasi yo'q / No benefit" },
  { id: 247, front: "得然", back: "とく — Tabiiyki / Naturally" },
  { id: 248, front: "得通", back: "Tokutsu / Tokutsu" },
  { id: 249, front: "徳客は表んだ", back: "とく — Yaxshi mijoz paydo bo'ldi / The virtuous customer appeared" },
  { id: 250, front: "心をこめて", back: "こころをこめて — Butun qalbim bilan / With all my heart" },
  { id: 251, front: "心做", back: "こころなし — samimiy / heartfelt" },
  { id: 252, front: "必然", back: "ひつぜん — muqarrar / inevitable" },
  { id: 253, front: "忘え", back: "え — unut / forget" },
  { id: 254, front: "忘り", back: "わすれられるけんり — unut / forget" },
  { id: 255, front: "忙しくて", back: "いそがしい — Men bandman / I'm busy" },
  { id: 256, front: "思いき", back: "おもいきって — Fikrlar / Thoughts" },
  { id: 257, front: "思いやって", back: "おもいやる — e'tiborli bo'ling / be considerate" },
  { id: 258, front: "思いやる", back: "おもいやる — e'tiborli / considerate" },
  { id: 259, front: "思い出される", back: "おもいだす — eslab qolish / be remembered" },
  { id: 260, front: "思い出すまい", back: "おもいだす — Esimda yo‘q / I don't remember" },
  { id: 261, front: "思い出すものだ", back: "おもいだす — Bu menga eslatadi / It reminds me" },
  { id: 262, front: "思い出す限りだ", back: "おもいだす — Esimda qolganicha / As far as I can remember" },
  { id: 263, front: "思うばかり", back: "おもう — Shunchaki o'ylab / Just thinking about it" },
  { id: 264, front: "思えばこそ", back: "おもう — Agar o'ylab ko'rsangiz / If you think about it" },
  { id: 265, front: "思えばさえ", back: "おもう — Men bu haqda o'ylasam ham / Even if I think about it" },
  { id: 266, front: "思ってさえ", back: "おもう — Hatto bu haqda o'ylash / Even thinking about it" },
  { id: 267, front: "思わされて", back: "meni o'ylashga majbur qildi / made me think" },
  { id: 268, front: "怠え很豆眼", back: "だるい — Dangasa kichkina yigit / Lazy little guy" },
  { id: 269, front: "恋し機のほう", back: "こいしい — Koishiki tomoni / Koishiki side" },
  { id: 270, front: "恥じらう", back: "はじらう — uyalmoq / be ashamed" },
  { id: 271, front: "恥じる", back: "はじる — uyalmoq / be ashamed" },
  { id: 272, front: "恥ずかしい", back: "はずかしい — uyatli / embarrassing" },
  { id: 273, front: "恥ずかしく", back: "はずかし・い — uyatli / embarrassing" },
  { id: 274, front: "恥をかく", back: "はじをかく — sharmanda qilish / embarrass" },
  { id: 275, front: "恵す", back: "えびす — baraka ber / bless" },
  { id: 276, front: "患者", back: "かんじゃ — sabr / patient" },
  { id: 277, front: "悩まされて", back: "なやます — bezovta / troubled" },
  { id: 278, front: "悩まれてい", back: "なやむ — Men xavotirdaman / I'm worried" },
  { id: 279, front: "悩みにほ", back: "なやみ — Qiyinchilikda / In trouble" },
  { id: 280, front: "悩むよりほ", back: "なやむ — Bu tashvishlanishdan yaxshiroqdir / It's better than worrying" },
  { id: 281, front: "悪いやり", back: "わるい — omadsizlik / bad luck" },
  { id: 282, front: "悪いる", back: "わるい — Bu yomon / It's bad" },
  { id: 283, front: "悪真に言って", back: "あく — rostini aytsam / honestly say" },
  { id: 284, front: "悪習", back: "あくしゅう — yomon odatlar / bad habits" },
  { id: 285, front: "想止你来西帯回来", back: "G'arbiy kamarga fikrlar keladi / Thoughts are coming to the west belt" },
  { id: 286, front: "意をし", back: "い — ehtiyot bo'ling / be careful" },
  { id: 287, front: "意志", back: "いし — bo'ladi / will" },
  { id: 288, front: "感器", back: "sensor / sensor" },
  { id: 289, front: "感心", back: "かんしん — taassurot qoldirdi / impressed" },
  { id: 290, front: "慰める", back: "なぐさめる — qulaylik / comfort" },
  { id: 291, front: "憎む", back: "にくむ — nafrat / hate" },
  { id: 292, front: "憎悪", back: "ぞうお — nafrat / hatred" },
  { id: 293, front: "憎感", back: "nafrat / hatred" },
  { id: 294, front: "憧道理", back: "りょうり — sog'inish printsipi / longing principle" },
  { id: 295, front: "成功", back: "せいこう — muvaffaqiyat / success" },
  { id: 296, front: "成績だった", back: "せいせき — Bu baholar edi / It was the grades" },
  { id: 297, front: "我正是你着想", back: "われ — Men haqman va siz bu fikrni o'ylab topdingiz. / I am right and you came up with this idea." },
  { id: 298, front: "所以", back: "ゆえん — Sabab / Reason" },
  { id: 299, front: "手がなくて", back: "て — Mening qo'llarim yo'q / I don't have any hands" },
  { id: 300, front: "手を抜いて", back: "て — kesilgan burchaklar / cut corners" },
  { id: 301, front: "手入れ", back: "ていれ — g'amxo'rlik / care" },
  { id: 302, front: "手当て", back: "てあて — davolash / treatment" },
  { id: 303, front: "手数", back: "てすう — qadamlar soni / number of steps" },
  { id: 304, front: "手配", back: "てはい — tartibga solish / arrangement" },
  { id: 305, front: "手順", back: "てじゅん — tartib / procedure" },
  { id: 306, front: "打折", back: "Buzilish / Breakdown" },
  { id: 307, front: "承ください", back: "しょう — Iltimos, qabul qiling / Please accept" },
  { id: 308, front: "招かれた", back: "まねく — taklif qilingan / invited" },
  { id: 309, front: "招く", back: "まねく — taklif qiling / invite" },
  { id: 310, front: "招待", back: "しょうたい — taklifnoma / invitation" },
  { id: 311, front: "招致", back: "しょうち — taklifnoma / invitation" },
  { id: 312, front: "振る舞う", back: "ふるまう — o'zini tutish / behave" },
  { id: 313, front: "採掘する", back: "さいくつ — meniki / mine" },
  { id: 314, front: "提出", back: "ていしゅつ — topshirish / submission" },
  { id: 315, front: "換えたほう", back: "かえる — Men uni o'zgartirishim kerak / I should change it" },
  { id: 316, front: "携断する", back: "する — amalga oshirish / to carry out" },
  { id: 317, front: "摂入", back: "とる — qabul qilish / intake" },
  { id: 318, front: "改対", back: "かい — qayta ko'rib chiqish / revision" },
  { id: 319, front: "教えてくだ", back: "おしえる — Iltimos, ayting / Please tell me" },
  { id: 320, front: "数人的性命", back: "いのち — bir nechta jinsiy hayot / several sexual lives" },
  { id: 321, front: "敷なやわい", back: "Yumshoq va yumshoq / Soft and soft" },
  { id: 322, front: "料速", back: "Yuk tashish tezligi / Shipping speed" },
  { id: 323, front: "新しい", back: "あたらし・い — yangi / new" },
  { id: 324, front: "新しい裏を買った", back: "Men yangi orqa sotib oldim / I bought a new back" },
  { id: 325, front: "新しい車を買った", back: "yangi mashina sotib oldi / bought a new car" },
  { id: 326, front: "新しく省", back: "yangi vazirlik / new ministry" },
  { id: 327, front: "新しく鶯", back: "Yangi bulbul / New nightingale" },
  { id: 328, front: "新的", back: "yangi / new" },
  { id: 329, front: "新的省能源的系統", back: "Yangi energiya tejash tizimi / New energy saving system" },
  { id: 330, front: "无起", back: "Voqea yo'q / No occurrence" },
  { id: 331, front: "日刊印", back: "kundalik muhr / daily seal" },
  { id: 332, front: "日台", back: "Yaponiya - Tayvan / Japan-Taiwan" },
  { id: 333, front: "日日", back: "にちにち — Kun kuni / Day day" },
  { id: 334, front: "日目", back: "kun / day" },
  { id: 335, front: "日程表によれば", back: "Marshrutga ko'ra / According to the itinerary" },
  { id: 336, front: "映画", back: "えいが — kino / movie" },
  { id: 337, front: "昨日", back: "きそ — kecha / yesterday" },
  { id: 338, front: "時計", back: "とけい — soat / clock" },
  { id: 339, front: "時間がたっぷ", back: "Ko'p vaqt / Lots of time" },
  { id: 340, front: "時間のずれ", back: "vaqt kechikishi / time lag" },
  { id: 341, front: "時間のむだだ", back: "Bu vaqtni behuda sarflash / It's a waste of time" },
  { id: 342, front: "普及によって", back: "ommalashtirish orqali / by popularization" },
  { id: 343, front: "暴る", back: "あば・る — fosh qilish / expose" },
  { id: 344, front: "更冷了", back: "Sovutish tugallandi / Cooling completed" },
  { id: 345, front: "書ができた", back: "Xattotlik tugallandi / The calligraphy was completed" },
  { id: 346, front: "書類", back: "しょるい — hujjatlar / documents" },
  { id: 347, front: "最浜の蓋煮", back: "Saihama go'shti / Saihama stew" },
  { id: 348, front: "最近の若者", back: "hozirgi yoshlar / young people these days" },
  { id: 349, front: "有値", back: "qimmatli / valuable" },
  { id: 350, front: "有意必", back: "Sezilarli darajada zarur / Significantly necessary" },
  { id: 351, front: "望は番口", back: "Istak - bu eshik / Desire is the gate" },
  { id: 352, front: "本をすくう", back: "kitob toping / scoop a book" },
  { id: 353, front: "本当は忠出身です", back: "Men aslida Tadashidanman / I'm actually from Tadashi" },
  { id: 354, front: "来月", back: "らいげつ — keyingi oy / next month" },
  { id: 355, front: "来週", back: "らいしゅう — keyingi hafta / next week" },
  { id: 356, front: "枚まとめて", back: "hammasi birga / all together" },
  { id: 357, front: "枚分", back: "dona / pieces" },
  { id: 358, front: "枚分まけてく", back: "Men buni siz bilan baham ko'raman. / I'll share it with you." },
  { id: 359, front: "柔軟", back: "じゅうなん — moslashuvchan / flexible" },
  { id: 360, front: "検査項目はすべて", back: "Barcha tekshiruv elementlari / All inspection items" },
  { id: 361, front: "検査項貝はすべて", back: "Barcha tekshirilgan mollyuskalar / All inspected shellfish" },
  { id: 362, front: "構義", back: "ma'nosi / meaning" },
  { id: 363, front: "構議", back: "taklif / proposal" },
  { id: 364, front: "横切る", back: "よこぎ・る — xoch / cross" },
  { id: 365, front: "横断歩導よこ", back: "piyodalar o'tish bo'yicha qo'llanma / crosswalk guide" },
  { id: 366, front: "機器", back: "きき — uskunalar / equipment" },
  { id: 367, front: "櫻母", back: "Sakuramo / Sakuramo" },
  { id: 368, front: "歌を聴く", back: "qo'shiqlar tinglash / listen to songs" },
  { id: 369, front: "歌を職く", back: "qo'shiqchi bo'lib ishlash / work as a singer" },
  { id: 370, front: "止です", back: "To'xtatildi / It's stopped" },
  { id: 371, front: "正義", back: "せいぎ — adolat / justice" },
  { id: 372, front: "歯舞するのぼ", back: "Tishlarini raqsga tushiradigan Nobo / Nobo who dances his teeth" },
  { id: 373, front: "母のこと", back: "Onam haqida / About my mother" },
  { id: 374, front: "母は僕の顔", back: "onam mening yuzim / mother is my face" },
  { id: 375, front: "気にしない", back: "Menga baribir / I don't care" },
  { id: 376, front: "気分が思い", back: "Men buni his qilyapman / I feel like it" },
  { id: 377, front: "気持ち", back: "きもち — tuyg'ular / feelings" },
  { id: 378, front: "水食", back: "すいしょく — suvli ovqat / water food" },
  { id: 379, front: "池添", back: "Ikezoe / Ikezoe" },
  { id: 380, front: "決められ", back: "belgilangan / determined" },
  { id: 381, front: "決められる", back: "き・める — qaror qabul qilish mumkin / can be decided" },
  { id: 382, front: "没有抗疾病", back: "kasallikning yo'qolishi / loss of disease" },
  { id: 383, front: "治ったから", back: "Chunki u tuzalib ketgan / Because it's healed" },
  { id: 384, front: "法了", back: "qonun / law" },
  { id: 385, front: "泣き始めた", back: "yig'lay boshladi / started crying" },
  { id: 386, front: "注ぐ", back: "そそ・ぐ — quying / pour" },
  { id: 387, front: "注入", back: "ちゅうにゅう — in'ektsiya / injection" },
  { id: 388, front: "注意している", back: "Men ehtiyotkorman / I'm careful" },
  { id: 389, front: "活説", back: "faol nazariya / active theory" },
  { id: 390, front: "流入", back: "りゅうにゅう — kirib kelishi / inflow" },
  { id: 391, front: "海る", back: "dengiz / sea" },
  { id: 392, front: "海度", back: "dengiz darajasi / sea degree" },
  { id: 393, front: "淡要", back: "Oddiy ma'lumot / Plain information" },
  { id: 394, front: "添付して送れる", back: "Qo'shimcha sifatida yuborilishi mumkin / Can be sent as an attachment" },
  { id: 395, front: "済み", back: "すみ — Bajarildi / Done" },
  { id: 396, front: "済む", back: "す・む — Tugallandi / Finished" },
  { id: 397, front: "済んでいる", back: "す・む — Allaqachon tayyor / Already done" },
  { id: 398, front: "温度", back: "おんど — harorat / temperature" },
  { id: 399, front: "温泉が出てきたそ", back: "Issiq buloq chiqdi / The hot spring came out" },
  { id: 400, front: "湿度", back: "しつど — namlik / humidity" },
  { id: 401, front: "湿気しめ", back: "namlik damperi / moisture damper" },
  { id: 402, front: "満満的", back: "Qoniqarli / Satisfied" },
  { id: 403, front: "漏らす", back: "もら・す — oqish / leak" },
  { id: 404, front: "漏掉", back: "oqish / leakage" },
  { id: 405, front: "漫画", back: "まんが — multfilm / cartoon" },
  { id: 406, front: "漬純", back: "Tuzlangan toza / Pickled pure" },
  { id: 407, front: "災害", back: "さいがい — falokat / disaster" },
  { id: 408, front: "災害が起こった時", back: "falokat sodir bo'lganda / when a disaster occurs" },
  { id: 409, front: "無い", back: "な・い — Yo'q / None" },
  { id: 410, front: "無いな無い", back: "Yo'q, yo'q, yo'q / No, no, no" },
  { id: 411, front: "無がてきた", back: "U ketdi / It's gone" },
  { id: 412, front: "無る", back: "yo'q / There is no" },
  { id: 413, front: "無境", back: "Cheksiz / Boundless" },
  { id: 414, front: "無然", back: "Begunoh / Innocent" },
  { id: 415, front: "無粋", back: "ぶすい — Sinfsiz / Unclassy" },
  { id: 416, front: "焦る", back: "あせ・る — sabr qil / be impatient" },
  { id: 417, front: "焦屋", back: "Jiaoya / Jiaoya" },
  { id: 418, front: "煮えさせら", back: "Keling, qaynatamiz / Let's boil it" },
  { id: 419, front: "煮える", back: "に・える — Qaynatib oling / Boil" },
  { id: 420, front: "煮癒する", back: "qaynatib oling va davolang / boil and heal" },
  { id: 421, front: "熊事", back: "Ayiq narsa / Bear thing" },
  { id: 422, front: "熟料品ふだ", back: "Pishgan oziq-ovqat chiqindilari / Ripe food waste" },
  { id: 423, front: "熱する", back: "ねっ・する — qizdiring / heat up" },
  { id: 424, front: "熱は会がいい", back: "Issiqlik yaxshi / The heat is good" },
  { id: 425, front: "熱感", back: "ねつかん — issiqlik hissi / heat sensation" },
  { id: 426, front: "父が亡くなった", back: "otam vafot etdi / my father died" },
  { id: 427, front: "父を尊敬している", back: "otamni hurmat qil / respect my father" },
  { id: 428, front: "独臭し", back: "Undan yolg'izlik hidi keladi / It smells solitary" },
  { id: 429, front: "率直に言って", back: "ochiqchasiga / frankly" },
  { id: 430, front: "玉社", back: "Tamasha / Tamasha" },
  { id: 431, front: "環境を守るため", back: "atrof-muhitni muhofaza qilish / to protect the environment" },
  { id: 432, front: "環境問題", back: "ekologik muammolar / environmental issues" },
  { id: 433, front: "環業料", back: "ekologik to'lovlar / environmental fees" },
  { id: 434, front: "生きがい", back: "いきがい — hayot maqsadi / purpose of life" },
  { id: 435, front: "生きがし", back: "hayot maqsadi / purpose of life" },
  { id: 436, front: "生じられた", back: "しょう・じる — paydo bo'ldi / arose" },
  { id: 437, front: "生じる", back: "しょう・じる — paydo bo'ladi / arise" },
  { id: 438, front: "生まれた順", back: "tug'ilish tartibi / birth order" },
  { id: 439, front: "生地な手", back: "xamirli qo'llar / doughy hands" },
  { id: 440, front: "生存的値", back: "omon qolish qiymati / survival value" },
  { id: 441, front: "用旧物銭換新物", back: "eski narsalarni yangisini almashtirish / old item exchange new item" },
  { id: 442, front: "田中さん", back: "Janob Tanaka / Mr. Tanaka" },
  { id: 443, front: "由引入", back: "Chiqib ketish sababi / Reason for withdrawal" },
  { id: 444, front: "申し訳", back: "もうしわけ — Kechirasiz / I'm sorry" },
  { id: 445, front: "男外", back: "erkak bo'lmagan / non-male" },
  { id: 446, front: "画家", back: "がか — rassom / painter" },
  { id: 447, front: "番目", back: "つがいめ — th / th" },
  { id: 448, front: "疼得厉害", back: "og'riq va zarar / pain and harm" },
  { id: 449, front: "病気に何がある", back: "kasallik nima / what is the disease" },
  { id: 450, front: "病院", back: "びょういん — kasalxona / hospital" },
  { id: 451, front: "痛みがなく", back: "og'riqsiz / pain free" },
  { id: 452, front: "癒気にける", back: "shifobaxsh energiya bering / give healing energy" },
  { id: 453, front: "発掘する", back: "はっくつ — qazish / excavate" },
  { id: 454, front: "目標", back: "めじるし — maqsad / goal" },
  { id: 455, front: "目標表によれば", back: "Maqsadli jadvalga muvofiq / According to the target table" },
  { id: 456, front: "目立っていた", back: "Bu sezilarli edi / It was noticeable" },
  { id: 457, front: "直せない", back: "なお・す — Buni tuzatib bo‘lmaydi / Can't fix it" },
  { id: 458, front: "着急", back: "Shoshilinch yetib keling / Arrive urgently" },
  { id: 459, front: "確率", back: "かくりつ — ehtimollik / probability" },
  { id: 460, front: "確立", back: "かくりつ — tashkil etish / establishment" },
  { id: 461, front: "票います", back: "Men ovoz beraman / I'll vote" },
  { id: 462, front: "禁太する", back: "Taqiqlangan / Forbidden" },
  { id: 463, front: "私からする", back: "mendan qiling / do it from me" },
  { id: 464, front: "私たち", back: "わたしたち — biz / us" },
  { id: 465, front: "私たちが買える", back: "sotib olamiz / we can buy" },
  { id: 466, front: "私なり", back: "men / me" },
  { id: 467, front: "私のことだ", back: "Bu men haqimda / It's about me" },
  { id: 468, front: "私らしく", back: "Xuddi men kabi / Just like me" },
  { id: 469, front: "程度", back: "ていど — daraja / degree" },
  { id: 470, front: "立っていた", back: "turgan edi / was standing" },
  { id: 471, front: "立て替え", back: "たてかえ — O'zgartirish / Replacement" },
  { id: 472, front: "立て替えて", back: "たてか・える — Uni almashtiring / Replace it" },
  { id: 473, front: "競馬する", back: "ot poygasi / race a horse" },
  { id: 474, front: "答え", back: "いらえ — javob / answer" },
  { id: 475, front: "範囲", back: "はんい — diapazon / range" },
  { id: 476, front: "粟年数", back: "tariq yoshi / millet age" },
  { id: 477, front: "納合された", back: "kelishilgan / agreed" },
  { id: 478, front: "納得", back: "なっとく — Qoniqarli / Satisfied" },
  { id: 479, front: "納得がいく", back: "Mantiqiy / Makes sense" },
  { id: 480, front: "素導", back: "Sodo / Sodo" },
  { id: 481, front: "素敷に受け入れ", back: "Ikkilanmasdan qabul qilinadi / Accepted without hesitation" },
  { id: 482, front: "素軟", back: "Yumshoq / Soft" },
  { id: 483, front: "紫的", back: "binafsha / purple" },
  { id: 484, front: "経不住誘惑", back: "Ishsiz qolish vasvasasi / Temptation to become unemployed" },
  { id: 485, front: "絡しいあい", back: "o'zaro bog'langan / intertwined" },
  { id: 486, front: "絵をひねる", back: "rasmni aylantiring / twist the picture" },
  { id: 487, front: "総選", back: "umumiy saylov / general election" },
  { id: 488, front: "編み物", back: "あみもの — trikotaj / knitting" },
  { id: 489, front: "編む", back: "あ・む — trikotaj / knit" },
  { id: 490, front: "編集", back: "へんしゅう — Tahrirlash / Edit" },
  { id: 491, front: "練の漫画", back: "Ren manga / Ren's manga" },
  { id: 492, front: "義務", back: "ぎむ — burch / duty" },
  { id: 493, front: "義理", back: "ぎり — majburiyat / obligation" },
  { id: 494, front: "聞いたとこ", back: "Men eshitgan narsam / What I heard" },
  { id: 495, front: "肌", back: "き — teri / skin" },
  { id: 496, front: "肖然", back: "oddiy / simple" },
  { id: 497, front: "胃に管を通す", back: "oshqozonga naycha o'tkazing / pass a tube into the stomach" },
  { id: 498, front: "能理解", back: "Tushunish yo'q / Noh understanding" },
  { id: 499, front: "腹題", back: "uy vazifasi / homework" },
  { id: 500, front: "膩頃", back: "Vaqt atrofida / Around the time" },
  { id: 501, front: "自の累身形", back: "o'z tana shakli / own body shape" },
  { id: 502, front: "自敷公とう", back: "Xususiy turar joy / Private residence" },
  { id: 503, front: "自然", back: "しぜん — tabiat / nature" },
  { id: 504, front: "自負", back: "じふ — g'urur / pride" },
  { id: 505, front: "致力", back: "kuch / power" },
  { id: 506, front: "舞う", back: "ま・う — raqsga tushish / dance" },
  { id: 507, front: "舞台でるなん", back: "Men sahnadaman / I'm on stage" },
  { id: 508, front: "舞台で踊るなんて", back: "Sahnada raqsga tushish uchun / To dance on stage" },
  { id: 509, front: "舞台衣装を着る", back: "sahna liboslarini kiyish / wear stage costumes" },
  { id: 510, front: "舞食", back: "Mayshoku / Maishoku" },
  { id: 511, front: "良い", back: "い・い — yaxshi / good" },
  { id: 512, front: "良いところ", back: "yaxshi nuqtalar / good points" },
  { id: 513, front: "良き", back: "よき — yaxshi / good" },
  { id: 514, front: "良好です", back: "りょうこう — Yaxshi / Good" },
  { id: 515, front: "良質", back: "りょうしつ — yaxshi sifat / good quality" },
  { id: 516, front: "色々考えた結果", back: "Turli fikrlar natijasida / As a result of various thoughts" },
  { id: 517, front: "芝説的活", back: "Shiba nazariyasi hayot / Shiba theory life" },
  { id: 518, front: "花送", back: "Gullarni yetkazib berish / Flower delivery" },
  { id: 519, front: "若いころ", back: "yoshligimda / when I was young" },
  { id: 520, front: "荒らす", back: "あら・す — vandal qilish / vandalize" },
  { id: 521, front: "荒れた肌がすべす", back: "Qo'pol terini tekislaydi / Smoothes rough skin" },
  { id: 522, front: "荒れた駅がすべす", back: "Dag'al stantsiya silliq / The rough station is smooth" },
  { id: 523, front: "荒れる", back: "あ・れる — qo'pol bo'lish / become rough" },
  { id: 524, front: "落ちゃん", back: "Fall-chan / Fall-chan" },
  { id: 525, front: "蒸い", back: "Bug'li / Steamy" },
  { id: 526, front: "蒸し", back: "むし — bug'langan / steamed" },
  { id: 527, front: "蒸らかい", back: "Bug'li / Steamy" },
  { id: 528, front: "薬も効かない", back: "Dori ham ishlamaydi / Medicine doesn't work either" },
  { id: 529, front: "薬を飲んだ", back: "dori oldi / took medicine" },
  { id: 530, front: "薬張する", back: "dorivor / medicinal" },
  { id: 531, front: "行かずに済ん", back: "Men borishim shart emas edi / I didn't have to go" },
  { id: 532, front: "行く", back: "い・く — ket / go" },
  { id: 533, front: "行くぐらい", back: "Ketish arafasida / About to go" },
  { id: 534, front: "行けない", back: "い・く — Men bora olmayman / I can't go" },
  { id: 535, front: "行っ", back: "おこな・う — ket / go" },
  { id: 536, front: "行ったかい", back: "Bordingmi? / Did you go?" },
  { id: 537, front: "行って", back: "おこな・う — ket / go" },
  { id: 538, front: "表のすぐそ", back: "stol yonida / right next to the table" },
  { id: 539, front: "表参", back: "jadvalga havola / table reference" },
  { id: 540, front: "袋愕", back: "Dahshatli / Shocking" },
  { id: 541, front: "袋素が起こった時", back: "Xalta materiali paydo bo'lganda / When bag material occurred" },
  { id: 542, front: "製像", back: "haykal yasash / statue making" },
  { id: 543, front: "製品を作りたい", back: "Men mahsulot yaratmoqchiman / I want to make a product" },
  { id: 544, front: "要する", back: "よう・する — Bu oladi / It takes" },
  { id: 545, front: "見たなり", back: "Men ko'rgan zahoti / As soon as I saw it" },
  { id: 546, front: "見る", back: "みる — qarang / see" },
  { id: 547, front: "見るなり", back: "Men buni ko'rishim bilanoq / As soon as I see it" },
  { id: 548, front: "見舞い", back: "みまい — Tashrif / Visitation" },
  { id: 549, front: "見舞う", back: "みま・う — tashrif buyuring / visit" },
  { id: 550, front: "言える", back: "い・える — Aytishim mumkin / I can say it" },
  { id: 551, front: "言えるが", back: "Men shuni aytishim mumkin / I can say that" },
  { id: 552, front: "言われて", back: "い・う — aytilmoqda / being told" },
  { id: 553, front: "言われる", back: "い・う — aytilsin / be told" },
  { id: 554, front: "言度恥をかけば", back: "Agar so'zlaringizdan uyalsangiz / If you are ashamed of your words" },
  { id: 555, front: "計画", back: "けいかく — reja / plan" },
  { id: 556, front: "訳ありませ", back: "Hech qanday sabab yo'q / There's no reason" },
  { id: 557, front: "診惑に負ける", back: "tashxisga berilish / succumb to diagnosis" },
  { id: 558, front: "試験", back: "しけん — imtihon / exam" },
  { id: 559, front: "詰まってい", back: "tiqilib qolgan / clogged" },
  { id: 560, front: "話がつか", back: "Men aytadigan gapim bor / I have something to say" },
  { id: 561, front: "話がつく", back: "はなし — Men gaplasha olaman / I can talk" },
  { id: 562, front: "話がわから", back: "Men hikoyani tushunmayapman / I don't understand the story" },
  { id: 563, front: "話がわかる", back: "話が分か・る — Men hikoyani tushunaman / I understand the story" },
  { id: 564, front: "話が事素だとすれ", back: "Agar voqea voqea bo'lsa / If the story is the matter" },
  { id: 565, front: "話になら", back: "Bu haqda gapirish / Talking about it" },
  { id: 566, front: "話にのら", back: "Hikoyaga kiring / Get into the story" },
  { id: 567, front: "話に乗る", back: "はなし — suhbatga kirish / get into the conversation" },
  { id: 568, front: "課程", back: "かてい — kurs / course" },
  { id: 569, front: "講義", back: "こうぎ — ma'ruza / lecture" },
  { id: 570, front: "講議", back: "ma'ruza / lecture" },
  { id: 571, front: "貝標が高ければこ", back: "Agar qobiq belgisi baland bo'lsa, unda / If the shell mark is high, then" },
  { id: 572, front: "負けてしま", back: "yutqazdim / I lost" },
  { id: 573, front: "財布を忘れた", back: "Men hamyonimni unutibman / I forgot my wallet" },
  { id: 574, front: "財産の相続で兄弟", back: "Mulkni meros qilib olgan birodarlar / Siblings inheriting property" },
  { id: 575, front: "買い", back: "かい — Sotib olish / Buy" },
  { id: 576, front: "買いに行った", back: "xarid qildi / went shopping" },
  { id: 577, front: "買い人のやるこ", back: "Xaridorning harakati / Buyer's action" },
  { id: 578, front: "買い換えたほう", back: "Yangisini sotib olish yaxshiroqdir / Better buy a new one" },
  { id: 579, front: "買ったら", back: "か・う — Agar siz sotib olsangiz / If you buy it" },
  { id: 580, front: "買ってきて", back: "sotib oling / buy it" },
  { id: 581, front: "貸しみ", back: "qarz / loan" },
  { id: 582, front: "貸む", back: "qarz berish / lend" },
  { id: 583, front: "貸らしい", back: "Ijaraga olinganga o'xshaydi / It seems to be rented" },
  { id: 584, front: "資料は悪港せ", back: "Materiallar yomon portlardir. / The materials are bad ports." },
  { id: 585, front: "資料は郵送", back: "Materiallar pochta orqali yuboriladi / Materials will be sent by mail" },
  { id: 586, front: "質度", back: "sifat / quality" },
  { id: 587, front: "贈品", back: "sovg'a / gift" },
  { id: 588, front: "赤ん坊", back: "あかんぼう — chaqaloq / baby" },
  { id: 589, front: "赤ん等", back: "Chaqaloqlar va boshqalar. / Babies etc." },
  { id: 590, front: "赤ん落", back: "chaqaloq tushishi / baby drop" },
  { id: 591, front: "足または姉", back: "oyoqlari yoki katta opasi / legs or older sister" },
  { id: 592, front: "足球排成一排", back: "Eksklyuziv futbol / Football exclusive" },
  { id: 593, front: "転居する", back: "てんきょ — harakat / move" },
  { id: 594, front: "辛口", back: "からくち — Quruq / Dry" },
  { id: 595, front: "辞めたい", back: "や・める — Men tark etmoqchiman / I want to quit" },
  { id: 596, front: "返還しません", back: "qaytarilmaydi / will not be returned" },
  { id: 597, front: "途中から雨", back: "O‘rtada yomg‘ir yog‘a boshladi / It started raining in the middle" },
  { id: 598, front: "連絡してくだ", back: "Iltimos, men bilan bog'laning / Please contact me" },
  { id: 599, front: "週間家", back: "haftalik uy / weekly house" },
  { id: 600, front: "遊く", back: "o'ynash / play" },
  { id: 601, front: "遊んでいる", back: "あす・ぶ — o'ynamoqda / playing" },
  { id: 602, front: "過ごした", back: "すご・す — sarflangan / spent" },
  { id: 603, front: "過程", back: "かてい — jarayon / process" },
  { id: 604, front: "過程を表したもの", back: "jarayonni ifodalovchi narsa / something that represents a process" },
  { id: 605, front: "道番にくにい", back: "Doban Nikuniy / Doban Nikunii" },
  { id: 606, front: "達成感も増す", back: "Muvaffaqiyat tuyg'usining kuchayishi / Increased sense of accomplishment" },
  { id: 607, front: "違い", back: "たがい — farq / difference" },
  { id: 608, front: "選まがずら", back: "tanlash / choice" },
  { id: 609, front: "選手", back: "せんしゅ — futbolchi / player" },
  { id: 610, front: "部品", back: "ぶひん — qismlar / parts" },
  { id: 611, front: "配得者", back: "distribyutor / distributor" },
  { id: 612, front: "酒ができた", back: "Spirtli ichimliklar tayyor / Alcohol is ready" },
  { id: 613, front: "酒をしなけ", back: "spirtli ichimlik ichmang / don't drink alcohol" },
  { id: 614, front: "醤富", back: "Shotomi / Shotomi" },
  { id: 615, front: "醤魔する", back: "soyaga / to soybean" },
  { id: 616, front: "金", back: "かね — oltin / gold" },
  { id: 617, front: "金の気持ちに関し", back: "Pulga nisbatan his-tuyg'ular haqida / Regarding feelings about money" },
  { id: 618, front: "釜が亡くなった", back: "qozon o'ldi / the pot died" },
  { id: 619, front: "鈍い", back: "おそ・い — zerikarli / dull" },
  { id: 620, front: "鈍感", back: "どんかん — befarqlik / insensitivity" },
  { id: 621, front: "鈍感だ", back: "どんかん — Bu befarq / It's insensitive" },
  { id: 622, front: "銅感", back: "Mis hissi / Copper feeling" },
  { id: 623, front: "鋭い", back: "すすど・い — keskin / sharp" },
  { id: 624, front: "鋭するど", back: "keskin o'tkir / sharp sharp" },
  { id: 625, front: "鋭感", back: "えいかん — keskin tuyg'u / keen sense" },
  { id: 626, front: "錯位", back: "chalkashlik / confusion" },
  { id: 627, front: "長い", back: "なが・い — uzoq / long" },
  { id: 628, front: "長編分短編", back: "uzun uzun qisqa hikoya / long length short story" },
  { id: 629, front: "間に合いかねる", back: "Men buni vaqtida uddalay olmayman / I can't make it in time" },
  { id: 630, front: "間に合いがたい", back: "Buni o'z vaqtida qilish qiyin / It's hard to make it in time" },
  { id: 631, front: "間に合いそう", back: "まにあ・う — O'z vaqtida bo'ladiganga o'xshaydi / Looks like it'll be on time" },
  { id: 632, front: "間に合うわけ", back: "Men buni vaqtida bajaraman / I'll make it in time" },
  { id: 633, front: "関し", back: "かん・する — Sekisei / Sekisei" },
  { id: 634, front: "降ってきて", back: "Pastga tush / Come down" },
  { id: 635, front: "集す", back: "yig'ish / collect" },
  { id: 636, front: "雨の降るかくり", back: "Yomg'ir yog'moqda / The rain is falling" },
  { id: 637, front: "雨季の場合は出", back: "Yomg'irli mavsumda / In the rainy season" },
  { id: 638, front: "雲敷する", back: "bulutlarni qoplaydi / cover the clouds" },
  { id: 639, front: "電事雲", back: "elektr buluti / electric cloud" },
  { id: 640, front: "電子", back: "でんし — elektron / electronic" },
  { id: 641, front: "電話", back: "でんわ — telefon / telephone" },
  { id: 642, front: "霧多", back: "Kirita / Kirita" },
  { id: 643, front: "青島", back: "あおしま — Qingdao / Qingdao" },
  { id: 644, front: "順序", back: "じゅんじょ — buyurtma / order" },
  { id: 645, front: "順番", back: "じゅんばん — buyurtma / order" },
  { id: 646, front: "頭が痛かった", back: "Boshim og'riyapti / My head hurt" },
  { id: 647, front: "頭は当分やみそう", back: "Boshim bir muncha vaqt ketayotganga o'xshaydi. / My head seems to be going away for a while." },
  { id: 648, front: "頭り", back: "bosh og'rig'i / headache" },
  { id: 649, front: "頭る", back: "bosh ko'taring / head up" },
  { id: 650, front: "頭痛がひどい", back: "Menda dahshatli bosh og'rig'i bor / I have a terrible headache" },
  { id: 651, front: "頭脳を持っている", back: "miyaga ega / have a brain" },
  { id: 652, front: "頭贈", back: "bosh sovg'asi / gift of head" },
  { id: 653, front: "食に対して", back: "oziq-ovqat uchun / for food" },
  { id: 654, front: "食べっぷり", back: "ko'p ovqat / plenty to eat" },
  { id: 655, front: "食をけなし", back: "Oziq-ovqatlarni yomonlash / Disparage food" },
  { id: 656, front: "食事するなら", back: "Agar siz ovqatlanmoqchi bo'lsangiz / If you want to eat" },
  { id: 657, front: "食要", back: "Ovqatlanish talablari / Meal requirements" },
  { id: 658, front: "養護師", back: "Hamshira / Nurse" },
  { id: 659, front: "首付", back: "Bo'yin bilan / With neck" },
  { id: 660, front: "駅着", back: "Stansiyaga yetib kelish / Arrive at station" },
  { id: 661, front: "高い", back: "たか・い — qimmat / expensive" },
  { id: 662, front: "高いお金をかけて", back: "ko'p pul sarflash / spend a lot of money" },
  { id: 663, front: "高婆代がかなり", back: "Takabaday juda katta / Takabadai is quite large" },
  { id: 664, front: "髪と寒くなる", back: "sochlar va sovuq / hair and getting cold" },
  { id: 665, front: "鬱営", back: "depressiya / depression" },
  { id: 666, front: "魚た", back: "Baliq / Fish" },
  { id: 667, front: "魚といい形といい", back: "Baliq va yaxshi shakl va yaxshi / Fish and good shape and good" },
  { id: 668, front: "鳴子", back: "なるこ — Naruko / Naruko" },
  { id: 669, front: "黒い", back: "くろ・い — qora / black" },
  { id: 670, front: "黒する", back: "qora rangga aylanadi / turn black" },
  { id: 671, front: "黒で行くとすれ", back: "Men qora rangda bo'lardim / I'd go with black" },
  { id: 672, front: "黒熱な手動き", back: "qorong'u qo'l harakatlari / dark hand movements" },
  { id: 673, front: "黒金", back: "qora oltin / black gold" },
];

export const deckGroups: DeckGroup[] = [
  {
    id: "Set-1",
    title: "Vocabulary 1-673",
    level: "JLPT N3/N2",
    startIndex: 1,
    endIndex: 673,
    cardCount: 673
  }
];

export function getCardsForGroup(groupId: string): Card[] {
  const group = deckGroups.find(g => g.id === groupId);
  if (!group) return [];
  
  return flashcards.filter(c => c.id >= group.startIndex && c.id <= group.endIndex);
}
