import type { Card, DeckGroup } from './types';

export const flashcards: Card[] = [
  { id: 1, front: "お供する", back: "おともする — birga bormoq, hamroh bo'lmoq / to accompany" },
  { id: 2, front: "落とし卵", back: "おとしたまご — cho'zilgan tuxum / poached egg" },
  { id: 3, front: "大口", back: "おおぐち — katta og'iz / big mouth, big talk, large sum" },
  { id: 4, front: "お名前", back: "おなまえ — ism / name (polite)" },
  { id: 5, front: "お問い合わせ番号", back: "おといあわせばんごう — so'rov raqami / inquiry/reference number" },
  { id: 6, front: "お忙しいところ", back: "おいそがしいところ — band vaqtingizda / while you are busy (polite preface)" },
  { id: 7, front: "お手数をおかけします", back: "おてすうをおかけします — noqulaylik uchun uzr / sorry to trouble you" },
  { id: 8, front: "お皿", back: "おさら — laganda / plate, dish" },
  { id: 9, front: "お金など", back: "おかねなど — pul va hokazo / money and such" },
  { id: 10, front: "お願いがある", back: "おねがいがある — iltimosim bor / to have a request" },
  { id: 11, front: "お願いがある", back: "おねがいがある — iltimosim bor / to have a request" },
  { id: 12, front: "ご了承ください", back: "ごりょうしょうください — iltimos, tushunib qo'ying / please understand, please note" },
  { id: 13, front: "五文型", back: "ごぶんけい — beshta gap tuzilishi / the five basic sentence patterns" },
  { id: 14, front: "一つです", back: "ひとつです — bitta / it is one" },
  { id: 15, front: "一位", back: "いちい — birinchi o'rin / first place" },
  { id: 16, front: "一度", back: "いちど — bir marta / once, one time" },
  { id: 17, front: "一段", back: "いちだん — bir bosqich, yanada / a step, still more" },
  { id: 18, front: "一等", back: "いっとう — birinchi darajali / first class, first prize" },
  { id: 19, front: "一緒に行く", back: "いっしょにいく — birga bormoq / to go together" },
  { id: 20, front: "一首の歌", back: "いっしゅのうた — bitta she'r/qo'shiq / one poem/song" },
  { id: 21, front: "上司と気まずい", back: "じょうしときまずい — rahbar bilan noqulay / awkward with one's boss" },
  { id: 22, front: "上型", back: "うわがた — yuqori qolip / upper mold" },
  { id: 23, front: "下取り", back: "したどり — eski buyumni topshirib yangisini olish / trade-in" },
  { id: 24, front: "下取りする", back: "したどりする — trade-in qilmoq / to trade in" },
  { id: 25, front: "不成体統", back: "ふせいたいとう — tartibsizlik, uyat holat / disorderly, disgraceful state" },
  { id: 26, front: "世紀", back: "せいき — asr / century" },
  { id: 27, front: "世紀に完成した", back: "せいきにかんせいした — asrda tugallangan / completed in that century" },
  { id: 28, front: "丘", back: "おか — tepalik / hill" },
  { id: 29, front: "両方の子", back: "りょうほうのこ — ikkala bola / both children" },
  { id: 30, front: "両目", back: "りょうめ — ikkala ko'z / both eyes" },
  { id: 31, front: "並みの性質", back: "なみのせいしつ — o'rtacha xususiyat / average quality/nature" },
  { id: 32, front: "並んでいる", back: "ならんでいる — saf tortgan / lined up, in a row" },
  { id: 33, front: "中の仏像", back: "なかのぶつぞう — ichidagi budda haykali / Buddha statue inside" },
  { id: 34, front: "中の企画", back: "なかのきかく — ichidagi reja / plan inside" },
  { id: 35, front: "中三口", back: "ちゅうさんこう — o'rta uchta og'iz(qism) / middle three portions (referential guess)" },
  { id: 36, front: "中央改札", back: "ちゅうおうかいさつ — markaziy chipta tekshiruv darvozasi / central ticket gate" },
  { id: 37, front: "一目見る", back: "ひとめみる — bir qarashda ko'rmoq / to take a glance" },
  { id: 38, front: "予定がぎっしり", back: "よていがぎっしり — jadval to'la band / schedule is packed" },
  { id: 39, front: "事務", back: "じむ — idora ishi / office work, clerical work" },
  { id: 40, front: "事務職", back: "じむしょく — idora xodimi lavozimi / clerical/office job" },
  { id: 41, front: "事実だけあって", back: "じじつだけあって — faqat haqiqat bo'lgani uchun / precisely because it is a fact" },
  { id: 42, front: "事実だとすれば", back: "じじつだとすれば — agar bu haqiqat bo'lsa / if it is indeed a fact" },
  { id: 43, front: "事実どおり", back: "じじつどおり — haqiqatga muvofiq / as per the facts" },
  { id: 44, front: "事実のまま", back: "じじつのまま — haqiqat holicha / as it truly is" },
  { id: 45, front: "二部にわたる", back: "にぶにわたる — ikki qismga bo'lingan / spanning two parts" },
  { id: 46, front: "井目", back: "せいもく — go o'yinidagi berilgan tosh (handikap) / handicap stones in Go" },
  { id: 47, front: "亡くなる", back: "なくなる — vafot etmoq / to pass away" },
  { id: 48, front: "人の意見を尊重する", back: "ひとのいけんをそんちょうする — boshqalarning fikrini hurmat qilmoq / to respect others' opinions" },
  { id: 49, front: "人の魚を救う", back: "ひとのさかなをすくう — boshqalarning baliqlarini qutqarmoq / to save others' fish" },
  { id: 50, front: "今日はしっかり", back: "きょうはしっかり — bugun puxta / today, firmly/thoroughly" },
  { id: 51, front: "今日の豆", back: "きょうのまめ — bugungi loviya / today's beans" },
  { id: 52, front: "納得がいかない", back: "なっとくがいかない — qoniqarli emas / cannot accept, unconvinced" },
  { id: 53, front: "今要", back: "こんよう — hozirgi zarurat / current necessity (best-effort reading of rare compound)" },
  { id: 54, front: "仕事", back: "しごと — ish / work, job" },
  { id: 55, front: "仕事がすごく忙しい", back: "しごとがすごくいそがしい — ish juda band / work is extremely busy" },
  { id: 56, front: "仕事が私を", back: "しごとがわたしを — ish meni / work ... me (fragment of sentence)" },
  { id: 57, front: "仕事ぶり", back: "しごとぶり — ishlash uslubi / manner of working, work performance" },
  { id: 58, front: "他の漫画", back: "ほかのまんが — boshqa manga / other manga" },
  { id: 59, front: "以上", back: "いじょう — yuqorida aytilganlar, shu bilan tamom / the above, that's all" },
  { id: 60, front: "仮名", back: "かな — kana (yapon yozuvi) / kana (Japanese syllabary)" },
  { id: 61, front: "仮店舗", back: "かりてんぽ — vaqtinchalik do'kon / temporary store" },
  { id: 62, front: "仮認定", back: "かりにんてい — vaqtinchalik tan olish / provisional recognition/certification" },
  { id: 63, front: "企業が増えてきた", back: "きぎょうがふえてきた — kompaniyalar soni ko'paydi / the number of companies has increased" },
  { id: 64, front: "企画", back: "きかく — reja, loyiha / planning, project" },
  { id: 65, front: "会談", back: "かいだん — muzokara, uchrashuv / talks, meeting" },
  { id: 66, front: "会社", back: "かいしゃ — kompaniya / company" },
  { id: 67, front: "会社を辞めたい", back: "かいしゃをやめたい — ishdan bo'shamoqchiman / I want to quit the company" },
  { id: 68, front: "伯父の家には本がある", back: "おじのいえにはほんがある — amakimning uyida kitoblar bor / there are books at my uncle's house" },
  { id: 69, front: "配分", back: "はいぶん — taqsimot, bo'linish / allocation, division" },
  { id: 70, front: "但し", back: "ただし — biroq, biroq shart bilan / however, provided that" },
  { id: 71, front: "低下する", back: "ていかする — pasaymoq / to decline, to decrease" },
  { id: 72, front: "何と", back: "なんと — nima, qanday / what, how (exclamatory)" },
  { id: 73, front: "何とかなる", back: "なんとかなる — qandaydir yo'l topiladi / it will work out somehow" },
  { id: 74, front: "作った料理", back: "つくったりょうり — tayyorlangan taom / the dish that was made" },
  { id: 75, front: "修理する権利", back: "しゅうりするけんり — ta'mirlash huquqi / right to repair" },
  { id: 76, front: "修理するくらい", back: "しゅうりするくらい — ta'mirlash darajasida / to the extent of repairing" },
  { id: 77, front: "小惜しい", back: "こおしい — biroz afsuslanarli / a bit of a pity (rare form, best-effort)" },
  { id: 78, front: "値引き", back: "ねびき — chegirma / discount" },
  { id: 79, front: "値引きする", back: "ねびきする — chegirma qilmoq / to give a discount" },
  { id: 80, front: "値打ち", back: "ねうち — qiymat, qadr-qimmat / worth, value" },
  { id: 81, front: "偏差", back: "へんさ — og'ish / deviation" },
  { id: 82, front: "健康状態は良好です", back: "けんこうじょうたいはりょうこうです — sog'liq holati yaxshi / health condition is good" },
  { id: 83, front: "健康状態", back: "けんこうじょうたい — sog'liq holati / health condition" },
  { id: 84, front: "偶然", back: "ぐうぜん — tasodif / coincidence" },
  { id: 85, front: "催す", back: "もよおす — tashkil qilmoq, o'tkazmoq / to hold (an event), to feel (an urge)" },
  { id: 86, front: "像", back: "ぞう — haykal / statue, image" },
  { id: 87, front: "兄または姉", back: "あにまたはあね — aka yoki opa / older brother or older sister" },
  { id: 88, front: "先にします", back: "さきにします — birinchi qilaman / I'll do it first" },
  { id: 89, front: "先程", back: "さきほど — sal oldin / a little while ago, earlier" },
  { id: 90, front: "先輩", back: "せんぱい — katta hamkasb/aka-uka (mansabda) / senior (colleague, classmate)" },
  { id: 91, front: "光熱費", back: "こうねつひ — kommunal xarajatlar (gaz, suv, elektr) / utility expenses (gas, water, electricity)" },
  { id: 92, front: "入れる", back: "いれる — solmoq, qo'ymoq / to put in, insert" },
  { id: 93, front: "入場", back: "にゅうじょう — kirish (zalga, joyga) / admission, entrance" },
  { id: 94, front: "入学料", back: "にゅうがくりょう — o'quv muassasasiga kirish to'lovi / school entrance fee" },
  { id: 95, front: "入学費", back: "にゅうがくひ — o'qishga kirish xarajati / admission expenses" },
  { id: 96, front: "入学金", back: "にゅうがくきん — o'qishga kirish to'lovi / school admission fee" },
  { id: 97, front: "入学金", back: "にゅうがくきん — o'qishga kirish to'lovi / school admission fee" },
  { id: 98, front: "入場", back: "にゅうじょう — kirish (zalga, joyga) / admission, entrance" },
  { id: 99, front: "公感", back: "きょうかん — hamdardlik, hamfikrlik / sympathy, empathy" },
  { id: 100, front: "内臓", back: "ないぞう — ichki a'zolar / internal organs" },
  { id: 101, front: "内臓", back: "ないぞう — ichki a'zolar / internal organs" },
  { id: 102, front: "出す", back: "だす — chiqarmoq, tashqariga chiqarmoq / to take out, put out" },
  { id: 103, front: "出会う", back: "であう — uchrashmoq, duch kelmoq / to meet, encounter" },
  { id: 104, front: "出張する", back: "しゅっちょうする — xizmat safariga bormoq / to go on a business trip" },
  { id: 105, front: "出来る", back: "できる — bajarilmoq, qila olmoq / to be able to do, to be completed" },
  { id: 106, front: "分", back: "ふん — daqiqa / minute" },
  { id: 107, front: "分別", back: "ふんべつ — saralash, farqlash, mulohaza / discretion, sorting" },
  { id: 108, front: "分別", back: "ふんべつ — mulohaza, saralash / discretion, sorting" },
  { id: 109, front: "別入口", back: "べついりぐち — alohida kirish eshigi / separate entrance" },
  { id: 110, front: "削減する", back: "さくげんする — kamaytirmoq, qisqartirmoq / to reduce, cut down" },
  { id: 111, front: "助かる", back: "たすかる — najot topmoq, yengillashmoq / to be saved, to be helped" },
  { id: 112, front: "動画", back: "どうが — video / video" },
  { id: 113, front: "化粧水", back: "けしょうすい — loson (yuz uchun) / facial lotion, toner" },
  { id: 114, front: "講義", back: "こうぎ — ma'ruza / lecture" },
  { id: 115, front: "午後", back: "ごご — peshindan keyin / afternoon" },
  { id: 116, front: "午後は講義", back: "ごご・こうぎ — peshindan keyin ma'ruza bor / lecture is in the afternoon" },
  { id: 117, front: "単独", back: "たんどく — yolg'iz, mustaqil / alone, single-handed" },
  { id: 118, front: "単純", back: "たんじゅん — oddiy, sodda / simple" },
  { id: 119, front: "博士", back: "はかせ — doktor, olim (ilmiy daraja) / doctor, PhD holder" },
  { id: 120, front: "博士", back: "はかせ — doktor, olim / doctor, PhD holder" },
  { id: 121, front: "友情", back: "ゆうじょう — do'stlik / friendship" },
  { id: 122, front: "友達", back: "ともだち — do'st / friend" },
  { id: 123, front: "双子", back: "ふたご — egizaklar / twins" },
  { id: 124, front: "双子", back: "ふたご — egizaklar / twins" },
  { id: 125, front: "収入", back: "しゅうにゅう — daromad / income" },
  { id: 126, front: "叔母", back: "おば — xola, amma / aunt" },
  { id: 127, front: "取り上げる", back: "とりあげる — ko'tarib olmoq, mavzu qilmoq / to pick up, take up (a topic)" },
  { id: 128, front: "取り上げる", back: "とりあげる — ko'tarib olmoq, mavzu qilmoq / to pick up, take up" },
  { id: 129, front: "取り入れる", back: "とりいれる — kiritmoq, qabul qilmoq / to adopt, incorporate" },
  { id: 130, front: "取り入れる", back: "とりいれる — kiritmoq, qabul qilmoq / to adopt, incorporate" },
  { id: 131, front: "取り入れる", back: "とりいれる — kiritmoq, qabul qilmoq / to adopt, incorporate" },
  { id: 132, front: "取り戻す", back: "とりもどす — qaytarib olmoq / to take back, regain" },
  { id: 133, front: "取り組む", back: "とりくむ — shug'ullanmoq, hal qilishga urinmoq / to tackle, work on" },
  { id: 134, front: "取り組む", back: "とりくむ — shug'ullanmoq / to tackle, work on" },
  { id: 135, front: "取り込む", back: "とりこむ — ichiga olmoq, qabul qilmoq / to take in, incorporate" },
  { id: 136, front: "取り込む", back: "とりこむ — ichiga olmoq / to take in, incorporate" },
  { id: 137, front: "受ける", back: "うける — qabul qilmoq, olmoq / to receive, accept" },
  { id: 138, front: "受け入れる", back: "うけいれる — qabul qilmoq / to accept, receive" },
  { id: 139, front: "受領", back: "じゅりょう — qabul qilib olish / receipt, acceptance" },
  { id: 140, front: "古い", back: "ふるい — eski / old" },
  { id: 141, front: "開催", back: "かいさい — (yig'ilish/tadbir) o'tkazish / holding (an event)" },
  { id: 142, front: "可能", back: "かのう — mumkin / possible" },
  { id: 143, front: "可能性", back: "かのうせい — ehtimollik / possibility" },
  { id: 144, front: "台湾", back: "たいわん — Tayvan / Taiwan" },
  { id: 145, front: "号する", back: "ごうする — nomlanmoq, deb ataash / to be called, to style oneself" },
  { id: 146, front: "薬", back: "くすり — dori / medicine" },
  { id: 147, front: "合図", back: "あいず — ishora, belgi / signal, sign" },
  { id: 148, front: "義理", back: "ぎり — burch, majburiyat / duty, obligation" },
  { id: 149, front: "同じ失敗", back: "おなじしっぱい — xuddi shu xato / the same mistake" },
  { id: 150, front: "同情", back: "どうじょう — hamdardlik / sympathy" },
  { id: 151, front: "同様", back: "どうよう — o'xshash, xuddi shunday / similar, likewise" },
  { id: 152, front: "向こう", back: "むこう — narigi tomon, u yer / over there, beyond" },
  { id: 153, front: "君ならできる", back: "きみならできる — sen qila olasan / you can do it" },
  { id: 154, front: "君", back: "きみ — sen / you" },
  { id: 155, front: "呼吸", back: "こきゅう — nafas olish / breathing, respiration" },
  { id: 156, front: "哲学", back: "てつがく — falsafa / philosophy" },
  { id: 157, front: "問題", back: "もんだい — muammo / problem" },
  { id: 158, front: "喜ぶ", back: "よろこぶ — quvonmoq / to rejoice, be glad" },
  { id: 159, front: "因る", back: "よる — sababli bo'lmoq, bog'liq bo'lmoq / to be due to, depend on" },
  { id: 160, front: "比較", back: "ひかく — taqqoslash, nisbat / comparison" },
  { id: 161, front: "困る", back: "こまる — qiynalmoq, muammoga duch kelmoq / to be troubled, in trouble" },
  { id: 162, front: "国に帰る", back: "くににかえる — o'z mamlakatiga qaytmoq / to return to one's country" },
  { id: 163, front: "頭が痛い", back: "あたまがいたい — boshi og'rimoq / to have a headache" },
  { id: 164, front: "地域", back: "ちいき — mintaqa, hudud / region, area" },
  { id: 165, front: "地面を掘る", back: "じめんをほる — yerni qazmoq / to dig the ground" },
  { id: 166, front: "地面を撮る", back: "じめんをとる — yerni suratga olmoq / to photograph the ground" },
  { id: 167, front: "塔", back: "とう — minora / tower" },
  { id: 168, front: "塗りたて", back: "ぬりたて — yangi bo'yalgan / freshly painted" },
  { id: 169, front: "塾", back: "じゅく — repetitorlik maktabi / cram school" },
  { id: 170, front: "塾", back: "じゅく — repetitorlik maktabi / cram school" },
  { id: 171, front: "壁", back: "かべ — devor / wall" },
  { id: 172, front: "一書する", back: "いっしょする — bir xat yozmoq / to write a letter" },
  { id: 173, front: "変わっている", back: "かわっている — o'zgacha, g'alati / to be different, unusual" },
  { id: 174, front: "夏", back: "なつ — yoz / summer" },
  { id: 175, front: "夏至", back: "げし — yoz kunning eng uzun kuni / summer solstice" },
  { id: 176, front: "夏", back: "なつ — yoz / summer" },
  { id: 177, front: "多数", back: "たすう — ko'plik, ko'p sonli / large number, majority" },
  { id: 178, front: "多銭", back: "たせん — ko'p pul / a lot of money" },
  { id: 179, front: "夢中", back: "むちゅう — mukkasidan ketish, berilib ketish / absorbed, engrossed" },
  { id: 180, front: "大会", back: "たいかい — musobaqa, turnir / tournament, convention" },
  { id: 181, front: "大変だ", back: "たいへんだ — juda qiyin, og'ir / difficult, tough" },
  { id: 182, front: "削減", back: "さくげん — qisqartirish / reduction" },
  { id: 183, front: "天然", back: "てんねん — tabiiy / natural" },
  { id: 184, front: "失態", back: "しったい — qo'pol xato / blunder" },
  { id: 185, front: "失礼", back: "しつれい — beodoblik, qo'pollik / rudeness" },
  { id: 186, front: "好かない", back: "すかない — yoqmaydigan / disagreeable, not liked" },
  { id: 187, front: "嫌われる", back: "きらわれる — yomon ko'rilmoq, nafratlanmoq / to be hated" },
  { id: 188, front: "子供", back: "こども — bola / child" },
  { id: 189, front: "学費", back: "がくひ — o'qish to'lovi / tuition fee" },
  { id: 190, front: "安慰", back: "あんい — taskin, tasalli (yupatish) / consolation, comfort" },
  { id: 191, front: "安否", back: "あんぴ — omonlik-omonsizlik / safety, well-being" },
  { id: 192, front: "定義", back: "ていぎ — ta'rif / definition" },
  { id: 193, front: "実費", back: "じっぴ — haqiqiy xarajat / actual cost" },
  { id: 194, front: "客観", back: "きゃっかん — obyektivlik / objectivity" },
  { id: 195, front: "室温", back: "しつおん — xona harorati / room temperature" },
  { id: 196, front: "害虫", back: "がいちゅう — zararli hasharot / harmful insect, pest" },
  { id: 197, front: "家にいる", back: "いえにいる — uyda bo'lmoq / to be at home" },
  { id: 198, front: "家にこもる", back: "いえにこもる — uyda qamalib qolmoq / to stay shut up at home" },
  { id: 199, front: "家事", back: "かじ — uy ishlari / housework" },
  { id: 200, front: "容易にする", back: "よういにする — osonlashtirmoq / to make easy" },
  { id: 201, front: "容量", back: "ようりょう — sig'im, hajm / capacity" },
  { id: 202, front: "富む", back: "とむ — boy bo'lmoq, mo'l bo'lmoq / to be rich, abundant" },
  { id: 203, front: "富士", back: "ふじ — Fuji (tog' nomi) / Fuji (mountain name)" },
  { id: 204, front: "横", back: "よこ — yon tomon / side" },
  { id: 205, front: "想起", back: "そうき — yodga tushirish / recollection, recalling" },
  { id: 206, front: "生死", back: "せいし — tug'ilish va o'lim / life and death" },
  { id: 207, front: "居眠り", back: "いねむり — mudrab qolish / dozing off" },
  { id: 208, front: "居間", back: "いま — yashash xonasi / living room" },
  { id: 209, front: "岡", back: "おか — tepalik / hill" },
  { id: 210, front: "岩", back: "いわ — qoya, tosh / rock" },
  { id: 211, front: "依然", back: "いぜん — hamon, o'zgarmagan holda / still, as before" },
  { id: 212, front: "川", back: "かわ — daryo / river" },
  { id: 213, front: "工夫", back: "くふう — chora, tadbir, ixtiro / device, ingenuity" },
  { id: 214, front: "暖房費が大幅", back: "だんぼうひ — isitish xarajati katta miqdorda / heating cost is large" },
  { id: 215, front: "将来", back: "しょうらい — kelajak / future" },
  { id: 216, front: "帰る", back: "かえる — uyga qaytmoq / to go home, return" },
  { id: 217, front: "平らな所", back: "たいらなところ — tekis joy / flat place" },
  { id: 218, front: "平然と", back: "へいぜんと — sokin, xotirjam holda / calmly, unperturbed" },
  { id: 219, front: "平均", back: "へいきん — o'rtacha / average" },
  { id: 220, front: "平均的", back: "へいきんてき — o'rtacha, oddiy / average, typical" },
  { id: 221, front: "平和", back: "へいわ — tinchlik / peace" },
  { id: 222, front: "年代", back: "ねんだい — davr, yillar / era, generation" },
  { id: 223, front: "年数", back: "ねんすう — yillar soni / number of years" },
  { id: 224, front: "年月", back: "としつき — yil va oy, vaqt / years and months, time" },
  { id: 225, front: "年齢", back: "ねんれい — yosh / age" },
  { id: 226, front: "床につく", back: "とこにつく — yotmoq, kasal bo'lib yotmoq / to go to bed, be laid up" },
  { id: 227, front: "店の拡張工事", back: "みせのかくちょうこうじ — do'konni kengaytirish qurilishi / store expansion construction" },
  { id: 228, front: "店の暖房工事", back: "みせのだんぼうこうじ — do'kon isitish tizimi qurilishi / store heating construction" },
  { id: 229, front: "度の割合", back: "どのわりあい — daraja nisbati / degree ratio" },
  { id: 230, front: "引き口", back: "ひきぐち — tortish joyi, kirish eshigi / pull opening, entrance" },
  { id: 231, front: "傲慢", back: "ごうまん — takabburlik / arrogance" },
  { id: 232, front: "強調", back: "きょうちょう — urg'u berish, ta'kidlash / emphasis" },
  { id: 233, front: "本当に必要なこと", back: "ほんとうにひつようなこと — chindan ham zarur bo'lgan narsa / what is truly necessary" },
  { id: 234, front: "当番", back: "とうばん — navbatchilik / duty, turn" },
  { id: 235, front: "当止", back: "とうし — shu yerda to'xtash / stopping here" },
  { id: 236, front: "当て", back: "あて — maqsad, moljal / aim, expectation" },
  { id: 237, front: "当然だ", back: "とうぜんだ — albatta, tabiiy / of course, natural" },
  { id: 238, front: "当期", back: "とうき — joriy davr / current period" },
  { id: 239, front: "彼", back: "かれ — u (erkak) / he" },
  { id: 240, front: "彼", back: "かれ — u (erkak) / he" },
  { id: 241, front: "彼", back: "かれ — u (erkak) / he" },
  { id: 242, front: "彼", back: "かれ — u (erkak) / he" },
  { id: 243, front: "彼女", back: "かのじょ — u (ayol) / she" },
  { id: 244, front: "彼女", back: "かのじょ — u (ayol) / she" },
  { id: 245, front: "従って", back: "したがって — shuning uchun / therefore" },
  { id: 246, front: "得る", back: "える — olmoq, erishmoq / to gain, obtain" },
  { id: 247, front: "当然", back: "とうぜん — tabiiyki, albatta / naturally, of course" },
  { id: 248, front: "得意", back: "とくい — mohirlik, yaxshi ko'rish / good at, forte" },
  { id: 249, front: "得意客", back: "とくいきゃく — doimiy mijoz / regular customer" },
  { id: 250, front: "心を込めて", back: "こころをこめて — butun qalbdan / wholeheartedly" },
  { id: 251, front: "心なしか", back: "こころなしか — go'yoki, negadir shunday tuyuladi / somehow, as if" },
  { id: 252, front: "必然", back: "ひつぜん — muqarrarlik / inevitability" },
  { id: 253, front: "覚える", back: "おぼえる — eslab qolmoq / to remember" },
  { id: 254, front: "忘れられる", back: "わすれられる — unutilmoq / to be forgotten" },
  { id: 255, front: "忙しい", back: "いそがしい — band, mashg'ul / busy" },
  { id: 256, front: "思い切って", back: "おもいきって — jur'at qilib, qat'iy qaror bilan / boldly, resolutely" },
  { id: 257, front: "思いやる", back: "おもいやる — g'amxo'rlik qilmoq / to be considerate" },
  { id: 258, front: "思いやる", back: "おもいやる — g'amxo'rlik qilmoq / to be considerate" },
  { id: 259, front: "思い出される", back: "おもいだされる — eslanmoq, yodga tushmoq / to be recalled" },
  { id: 260, front: "思い出す", back: "おもいだす — eslab qolmoq, yodga tushirmoq / to remember, recall" },
  { id: 261, front: "思い出す", back: "おもいだす — eslab qolmoq, yodga tushirmoq / to remember, recall" },
  { id: 262, front: "思い出す", back: "おもいだす — eslab qolmoq, yodga tushirmoq / to remember, recall" },
  { id: 263, front: "思う", back: "おもう — o'ylamoq / to think" },
  { id: 264, front: "思えば", back: "おもえば — o'ylab qarasa / when one thinks about it" },
  { id: 265, front: "思う", back: "おもう — o'ylamoq / to think" },
  { id: 266, front: "思う", back: "おもう — o'ylamoq / to think" },
  { id: 267, front: "思わせる", back: "おもわせる — o'ylashga majbur qilmoq / to make someone think" },
  { id: 268, front: "怠ける", back: "なまける — dangasalik qilmoq / to be lazy, idle" },
  { id: 269, front: "恋しい", back: "こいしい — sog'ingan, qo'msagan / longed for, missed" },
  { id: 270, front: "恥じらう", back: "はじらう — uyalmoq, tortinmoq / to be bashful, shy" },
  { id: 271, front: "恥じる", back: "はじる — uyalmoq / to be ashamed" },
  { id: 272, front: "恥ずかしい", back: "はずかしい — uyatli, sharmandali / embarrassing, shameful" },
  { id: 273, front: "恥ずかしい", back: "はずかしい — uyatli, sharmandali / embarrassing, shameful" },
  { id: 274, front: "恥をかく", back: "はじをかく — sharmanda bo'lmoq / to be embarrassed, to lose face" },
  { id: 275, front: "恵む", back: "めぐむ — inoyat qilmoq, sadaqa bermoq / to bless, to give charity" },
  { id: 276, front: "患者", back: "かんじゃ — bemor / patient (medical)" },
  { id: 277, front: "悩まされる", back: "なやまされる — bezovta qilinmoq / to be troubled by, to be plagued by" },
  { id: 278, front: "悩む", back: "なやむ — xavotirlanmoq, qiynalmoq / to worry, to be distressed" },
  { id: 279, front: "悩み", back: "なやみ — tashvish, muammo / worry, trouble" },
  { id: 280, front: "悩む", back: "なやむ — xavotirlanmoq, qiynalmoq / to worry, to be distressed" },
  { id: 281, front: "悪いやり方", back: "わるいやりかた — yomon usul / bad way of doing something" },
  { id: 282, front: "悪い", back: "わるい — yomon / bad" },
  { id: 283, front: "率直に言って", back: "そっちょくにいって — rostini aytganda / to be honest, frankly speaking" },
  { id: 284, front: "悪習", back: "あくしゅう — yomon odat / bad habit, evil custom" },
  { id: 285, front: "持ち帰る", back: "もちかえる — olib qaytmoq / to take back, to bring home" },
  { id: 286, front: "意をする", back: "いをする — ehtiyot bo'lmoq, e'tibor bermoq / to pay attention, to be careful" },
  { id: 287, front: "意志", back: "いし — iroda / will, intention" },
  { id: 288, front: "感知器", back: "かんちき — sensor / sensor" },
  { id: 289, front: "感心", back: "かんしん — taassurot qoldirish, hayratlanish / admiration, being impressed" },
  { id: 290, front: "慰める", back: "なぐさめる — yupatmoq, tasalli bermoq / to comfort, to console" },
  { id: 291, front: "憎む", back: "にくむ — nafratlanmoq / to hate" },
  { id: 292, front: "憎悪", back: "ぞうお — nafrat / hatred" },
  { id: 293, front: "憎しみ", back: "にくしみ — nafrat / hatred" },
  { id: 294, front: "憧れる", back: "あこがれる — orzu qilmoq, sog'inmoq / to long for, to admire" },
  { id: 295, front: "成功", back: "せいこう — muvaffaqiyat / success" },
  { id: 296, front: "成績", back: "せいせき — baho, natija / grades, results" },
  { id: 297, front: "我が儘", back: "わがまま — o'zboshimchalik / selfishness, willfulness" },
  { id: 298, front: "所以", back: "ゆえん — sabab, sabab-oqibat / reason, the reason why" },
  { id: 299, front: "手がない", back: "てがない — qo'l yetishmaydi, ish kuchi yo'q / short-handed, no way to help" },
  { id: 300, front: "手を抜く", back: "てをぬく — ishni bekami-ko'st qilmoq / to cut corners" },
  { id: 301, front: "手入れ", back: "ていれ — parvarish qilish, g'amxo'rlik / maintenance, care" },
  { id: 302, front: "手当て", back: "てあて — davolash, nafaqa / treatment, allowance" },
  { id: 303, front: "手数", back: "てすう — mashaqqat, ovora / trouble, bother; number of steps" },
  { id: 304, front: "手配", back: "てはい — tayyorgarlik ko'rish / arrangement, procurement" },
  { id: 305, front: "手順", back: "てじゅん — tartib, protsedura / procedure" },
  { id: 306, front: "折半", back: "せっぱん — teng bo'lish (xarajatlarni) / splitting equally, going halves" },
  { id: 307, front: "承知する", back: "しょうちする — qabul qilmoq, rozi bo'lmoq / to accept, to consent" },
  { id: 308, front: "招く", back: "まねく — taklif qilmoq / to invite" },
  { id: 309, front: "招く", back: "まねく — taklif qilmoq / to invite" },
  { id: 310, front: "招待", back: "しょうたい — taklifnoma / invitation" },
  { id: 311, front: "招致", back: "しょうち — jalb qilish, taklif qilib olib kelish / attracting, bidding to host" },
  { id: 312, front: "振る舞う", back: "ふるまう — o'zini tutmoq / to behave, to conduct oneself" },
  { id: 313, front: "採掘する", back: "さいくつする — qazib olmoq / to mine, to extract" },
  { id: 314, front: "提出", back: "ていしゅつ — topshirish / submission" },
  { id: 315, front: "換える", back: "かえる — almashtirmoq / to exchange, to change" },
  { id: 316, front: "決断する", back: "けつだんする — qat'iy qaror qabul qilmoq / to make a decisive decision" },
  { id: 317, front: "摂取", back: "せっしゅ — qabul qilish (ovqat, vitamin) / intake, ingestion" },
  { id: 318, front: "改訂", back: "かいてい — qayta ko'rib chiqish / revision" },
  { id: 319, front: "教える", back: "おしえる — o'rgatmoq, aytmoq / to teach, to tell" },
  { id: 320, front: "生命", back: "せいめい — hayot, jon / life" },
  { id: 321, front: "柔らかい", back: "やわらかい — yumshoq / soft" },
  { id: 322, front: "速達", back: "そくたつ — tezpochta / express mail, special delivery" },
  { id: 323, front: "新しい", back: "あたらしい — yangi / new" },
  { id: 324, front: "裏を買う", back: "うらをかう — orqa (nusxa)ni sotib olmoq / to buy a back copy/side" },
  { id: 325, front: "新しい車を買う", back: "あたらしいくるまをかう — yangi mashina sotib olmoq / to buy a new car" },
  { id: 326, front: "省", back: "しょう — vazirlik / ministry" },
  { id: 327, front: "鶯", back: "うぐいす — bulbul (yapon bulbuli) / Japanese nightingale (bush warbler)" },
  { id: 328, front: "新的", back: "しんてき — yangi (xitoycha ta'sirdagi) / new (of the new type)" },
  { id: 329, front: "省エネルギーシステム", back: "しょうエネルギーシステム — energiya tejash tizimi / energy-saving system" },
  { id: 330, front: "想起", back: "そうき — eslash, esga tushirish / recollection, recalling" },
  { id: 331, front: "日刊", back: "にっかん — kundalik nashr / daily publication" },
  { id: 332, front: "日常", back: "にちじょう — kundalik hayot / everyday, daily life" },
  { id: 333, front: "日々", back: "ひび — kundan-kunga, har kuni / day by day, daily" },
  { id: 334, front: "日目", back: "にちめ — ...-kun (kunlarni sanash) / the ...th day (counter)" },
  { id: 335, front: "日程表", back: "にっていひょう — marshrut jadvali / itinerary, schedule" },
  { id: 336, front: "映画", back: "えいが — kino / movie" },
  { id: 337, front: "昨日", back: "きのう — kecha / yesterday" },
  { id: 338, front: "時計", back: "とけい — soat / clock, watch" },
  { id: 339, front: "時間がたっぷりある", back: "じかんがたっぷりある — ko'p vaqt bor / to have plenty of time" },
  { id: 340, front: "時間のずれ", back: "じかんのずれ — vaqt farqi / time lag, time difference" },
  { id: 341, front: "時間の無駄だ", back: "じかんのむだだ — bu vaqtni behuda sarflash / it's a waste of time" },
  { id: 342, front: "普及", back: "ふきゅう — keng tarqalish, ommalashish / spread, popularization" },
  { id: 343, front: "暴く", back: "あばく — fosh qilmoq / to expose, to reveal" },
  { id: 344, front: "冷える", back: "ひえる — sovib qolmoq / to get cold, to cool down" },
  { id: 345, front: "書道", back: "しょどう — xattotlik / calligraphy" },
  { id: 346, front: "書類", back: "しょるい — hujjatlar / documents" },
  { id: 347, front: "佃煮", back: "つくだに — shirin-shirin qaynatilgan taom / tsukudani (food simmered in soy sauce)" },
  { id: 348, front: "最近の若者", back: "さいきんのわかもの — hozirgi yoshlar / young people these days" },
  { id: 349, front: "価値", back: "かち — qiymat / value" },
  { id: 350, front: "有意義", back: "ゆういぎ — mazmunli, foydali / meaningful, significant" },
  { id: 351, front: "望み", back: "のぞみ — istak, umid / wish, hope" },
  { id: 352, front: "本を救う", back: "ほんをすくう — kitobni qutqarmoq / to rescue a book" },
  { id: 353, front: "出身", back: "しゅっしん — kelib chiqishi, tug'ilgan joyi / one's hometown, origin" },
  { id: 354, front: "来月", back: "らいげつ — keyingi oy / next month" },
  { id: 355, front: "来週", back: "らいしゅう — keyingi hafta / next week" },
  { id: 356, front: "まとめる", back: "まとめる — birlashtirmoq, to'plamoq / to gather together, to compile" },
  { id: 357, front: "枚分", back: "まいぶん — ...dona uchun / for the number of sheets/pieces" },
  { id: 358, front: "負ける", back: "まける — narxni tushirmoq, chegirma bermoq / to reduce a price, to give a discount" },
  { id: 359, front: "柔軟", back: "じゅうなん — moslashuvchan / flexible" },
  { id: 360, front: "検査項目", back: "けんさこうもく — tekshiruv bandi / inspection item" },
  { id: 361, front: "検査", back: "けんさ — tekshiruv / inspection" },
  { id: 362, front: "講義", back: "こうぎ — ma'ruza / lecture" },
  { id: 363, front: "抗議", back: "こうぎ — norozilik bildirish / protest" },
  { id: 364, front: "横切る", back: "よこぎる — kesib o'tmoq / to cross" },
  { id: 365, front: "横断歩道", back: "おうだんほどう — piyodalar o'tish joyi / crosswalk" },
  { id: 366, front: "機器", back: "きき — uskunalar / equipment" },
  { id: 367, front: "酵母", back: "こうぼ — xamirturush / yeast" },
  { id: 368, front: "歌を聴く", back: "うたをきく — qo'shiq tinglamoq / to listen to a song" },
  { id: 369, front: "歌を歌う", back: "うたをうたう — qo'shiq aytmoq / to sing a song" },
  { id: 370, front: "中止です", back: "ちゅうしです — bekor qilindi / it's cancelled" },
  { id: 371, front: "正義", back: "せいぎ — adolat / justice" },
  { id: 372, front: "歯磨きする", back: "はみがきする — tish yuvmoq / to brush teeth" },
  { id: 373, front: "母のこと", back: "ははのこと — onam haqida / about my mother" },
  { id: 374, front: "母は僕の顔を見る", back: "はははぼくのかおをみる — onam mening yuzimga qaraydi / mother looks at my face" },
  { id: 375, front: "気にしない", back: "きにしない — parvo qilmaslik / not to mind" },
  { id: 376, front: "気分が重い", back: "きぶんがおもい — kayfiyati og'ir / feeling low" },
  { id: 377, front: "気持ち", back: "きもち — tuyg'u / feeling" },
  { id: 378, front: "水食", back: "すいしょく — suv bilan yuvilish (eroziya) / water erosion" },
  { id: 379, front: "池", back: "いけ — hovuz / pond" },
  { id: 380, front: "決める", back: "きめる — qaror qilmoq / to decide" },
  { id: 381, front: "決められる", back: "きめられる — qaror qilish mumkin / can be decided" },
  { id: 382, front: "抵抗する", back: "ていこうする — qarshilik ko'rsatmoq / to resist" },
  { id: 383, front: "治る", back: "なおる — tuzalmoq / to heal, recover" },
  { id: 384, front: "法律", back: "ほうりつ — qonun / law" },
  { id: 385, front: "泣き始める", back: "なきはじめる — yig'lay boshlamoq / to start crying" },
  { id: 386, front: "注ぐ", back: "そそぐ — quymoq / to pour" },
  { id: 387, front: "注入", back: "ちゅうにゅう — quyish, in'ektsiya / injection, infusion" },
  { id: 388, front: "注意する", back: "ちゅういする — ehtiyot bo'lmoq / to be careful" },
  { id: 389, front: "学説", back: "がくせつ — ilmiy nazariya / academic theory" },
  { id: 390, front: "流入", back: "りゅうにゅう — kirib kelish / inflow" },
  { id: 391, front: "海", back: "うみ — dengiz / sea" },
  { id: 392, front: "海抜", back: "かいばつ — dengiz sathidan balandlik / elevation above sea level" },
  { id: 393, front: "概要", back: "がいよう — umumiy ma'lumot / summary, overview" },
  { id: 394, front: "添付して送れる", back: "てんぷしておくれる — biriktirib yuborish mumkin / can send as an attachment" },
  { id: 395, front: "済み", back: "すみ — bajarilgan / done, completed" },
  { id: 396, front: "済む", back: "すむ — tugamoq / to be finished" },
  { id: 397, front: "済んでいる", back: "すんでいる — tugallangan / already finished" },
  { id: 398, front: "温度", back: "おんど — harorat / temperature" },
  { id: 399, front: "温泉が出てきた", back: "おんせんがでてきた — issiq buloq chiqdi / a hot spring appeared" },
  { id: 400, front: "湿度", back: "しつど — namlik / humidity" },
  { id: 401, front: "湿気", back: "しっけ — namlik / dampness, moisture" },
  { id: 402, front: "満足的", back: "まんぞくてき — qoniqarli / satisfactory" },
  { id: 403, front: "漏らす", back: "もらす — sizdirmoq / to leak, let out" },
  { id: 404, front: "漏れる", back: "もれる — sizib chiqmoq / to leak" },
  { id: 405, front: "漫画", back: "まんが — komiks / manga, cartoon" },
  { id: 406, front: "純粋", back: "じゅんすい — toza, sof / pure" },
  { id: 407, front: "災害", back: "さいがい — falokat / disaster" },
  { id: 408, front: "災害が起こった時", back: "さいがいがおこったとき — falokat sodir bo'lganda / when a disaster occurs" },
  { id: 409, front: "無い", back: "ない — yo'q / nonexistent, not" },
  { id: 410, front: "無い無い", back: "ないない — yo'q-yo'q / no no (nothing at all)" },
  { id: 411, front: "無くなる", back: "なくなる — yo'qolmoq / to disappear, run out" },
  { id: 412, front: "無くなる", back: "なくなる — yo'q bo'lib qolmoq / to cease to exist" },
  { id: 413, front: "無限", back: "むげん — cheksiz / infinite, boundless" },
  { id: 414, front: "無罪", back: "むざい — aybsiz, begunoh / not guilty, innocent" },
  { id: 415, front: "無粋", back: "ぶすい — didsiz / unrefined, unclassy" },
  { id: 416, front: "焦る", back: "あせる — shoshilmoq, sabrsizlanmoq / to be impatient, panic" },
  { id: 417, front: "焦げ", back: "こげ — kuygan joy / scorch, burn mark" },
  { id: 418, front: "煮させる", back: "にさせる — qaynatdirmoq / to make someone boil something" },
  { id: 419, front: "煮える", back: "にえる — qaynamoq, pishmoq / to boil, cook" },
  { id: 420, front: "治癒する", back: "ちゆする — davolanmoq, tuzalmoq / to heal, be cured" },
  { id: 421, front: "熊", back: "くま — ayiq / bear" },
  { id: 422, front: "食料品", back: "しょくりょうひん — oziq-ovqat mahsulotlari / groceries, foodstuffs" },
  { id: 423, front: "熱する", back: "ねっする — qizdirmoq / to heat up" },
  { id: 424, front: "熱は下がった", back: "ねつはさがった — harorat tushdi / the fever went down" },
  { id: 425, front: "熱感", back: "ねっかん — issiqlik hissi / feeling of heat" },
  { id: 426, front: "父が亡くなる", back: "ちちがなくなる — otasi vafot etmoq / one's father passes away" },
  { id: 427, front: "父を尊敬している", back: "ちちをそんけいしている — otasini hurmat qilmoqda / respects one's father" },
  { id: 428, front: "孤独臭い", back: "こどくくさい — yolg'izlik hidi kelmoq / smelling of loneliness" },
  { id: 429, front: "率直に言って", back: "そっちょくにいって — ochig'ini aytganda / frankly speaking" },
  { id: 430, front: "神社", back: "じんじゃ — sinto ibodatxonasi / Shinto shrine" },
  { id: 431, front: "環境を守る", back: "かんきょうをまもる — atrof-muhitni himoya qilmoq / to protect the environment" },
  { id: 432, front: "環境問題", back: "かんきょうもんだい — ekologik muammolar / environmental issues" },
  { id: 433, front: "環境料金", back: "かんきょうりょうきん — ekologik to'lov / environmental fee" },
  { id: 434, front: "生きがい", back: "いきがい — hayot maqsadi / reason for living" },
  { id: 435, front: "生きがい", back: "いきがい — yashash mazmuni / purpose of life" },
  { id: 436, front: "生じる", back: "しょうじる — yuzaga kelmoq / to arise, occur" },
  { id: 437, front: "生じる", back: "しょうじる — paydo bo'lmoq / to arise" },
  { id: 438, front: "生まれた順", back: "うまれたじゅん — tug'ilish tartibi / birth order" },
  { id: 439, front: "生地", back: "きじ — mato, xamir / fabric, dough" },
  { id: 440, front: "生存的価値", back: "せいぞんてきかち — omon qolish qiymati / survival value" },
  { id: 441, front: "旧物を新物に換える", back: "きゅうぶつをしんぶつにかえる — eskini yangiga almashtirmoq / to exchange old things for new" },
  { id: 442, front: "田中さん", back: "たなかさん — Tanaka-san (janob Tanaka) / Mr. Tanaka" },
  { id: 443, front: "引退の理由", back: "いんたいのりゆう — nafaqaga chiqish sababi / reason for retirement" },
  { id: 444, front: "申し訳ない", back: "もうしわけない — kechirasiz / I'm sorry, inexcusable" },
  { id: 445, front: "男以外", back: "おとこいがい — erkakdan boshqa / other than male" },
  { id: 446, front: "画家", back: "がか — rassom / painter" },
  { id: 447, front: "番目", back: "ばんめ — -inchi (tartib son qo'shimchasi) / ordinal counter (-th)" },
  { id: 448, front: "疼く", back: "うずく — qattiq og'rimoq / to ache severely" },
  { id: 449, front: "病気は何がある", back: "びょうきはなにがある — kasallik nima ekanligi / what illness is there" },
  { id: 450, front: "病院", back: "びょういん — kasalxona / hospital" },
  { id: 451, front: "痛みがない", back: "いたみがない — og'riqsiz / painless" },
  { id: 452, front: "元気づける", back: "げんきづける — ruhlantirmoq, dalda bermoq / to cheer up, encourage" },
  { id: 453, front: "発掘する", back: "はっくつする — qazish, kashf etish / to excavate, unearth" },
  { id: 454, front: "目印", back: "めじるし — belgi, nishon / mark, landmark" },
  { id: 455, front: "目標", back: "もくひょう — maqsad / goal, target" },
  { id: 456, front: "目立つ", back: "めだつ — ko'zga tashlanmoq / to stand out, be noticeable" },
  { id: 457, front: "直す", back: "なおす — tuzatmoq / to fix, repair" },
  { id: 458, front: "着急", back: "ちゃっきゅう — shoshilinch yetib kelish / to arrive urgently" },
  { id: 459, front: "確率", back: "かくりつ — ehtimollik / probability" },
  { id: 460, front: "確立", back: "かくりつ — tashkil etish, mustahkamlash / establishment" },
  { id: 461, front: "投票する", back: "とうひょうする — ovoz bermoq / to vote" },
  { id: 462, front: "禁止する", back: "きんしする — taqiqlamoq / to prohibit, forbid" },
  { id: 463, front: "私からする", back: "わたしからする — mendan qilaman / I'll do it myself" },
  { id: 464, front: "私たち", back: "わたしたち — biz / we, us" },
  { id: 465, front: "買える", back: "かえる — sotib olish mumkin / can buy" },
  { id: 466, front: "私なりに", back: "わたしなりに — o'zimcha / in my own way" },
  { id: 467, front: "私のことだ", back: "わたしのことだ — bu men haqimda / it's about me" },
  { id: 468, front: "私らしく", back: "わたしらしく — o'zimga xos tarzda / in my own way, like myself" },
  { id: 469, front: "程度", back: "ていど — daraja / degree, extent" },
  { id: 470, front: "立つ", back: "たつ — turmoq / to stand" },
  { id: 471, front: "立て替え", back: "たてかえ — vaqtincha to'lash / advance payment (paying on someone's behalf)" },
  { id: 472, front: "立て替える", back: "たてかえる — o'rniga to'lab qo'ymoq / to pay on someone's behalf temporarily" },
  { id: 473, front: "競馬", back: "けいば — otchopar poygasi / horse racing" },
  { id: 474, front: "答え", back: "こたえ — javob / answer" },
  { id: 475, front: "範囲", back: "はんい — diapazon, chegara / range, scope" },
  { id: 476, front: "築年数", back: "ちくねんすう — qurilgan yildan beri o'tgan vaqt / age of a building" },
  { id: 477, front: "納得する", back: "なっとくする — kelishilmoq, tushunib qabul qilmoq / to be convinced, agreed" },
  { id: 478, front: "納得", back: "なっとく — qoniqish, tushunish / consent, understanding" },
  { id: 479, front: "納得がいく", back: "なっとくがいく — mantiqiy, tushunarli / to make sense" },
  { id: 480, front: "素質", back: "そしつ — qobiliyat, tabiiy xislat / innate quality, aptitude" },
  { id: 481, front: "素直に受け入れる", back: "すなおにうけいれる — ikkilanmasdan qabul qilmoq / to accept honestly without hesitation" },
  { id: 482, front: "素朴", back: "そぼく — sodda, yumshoq / simple, unaffected" },
  { id: 483, front: "紫色", back: "むらさきいろ — binafsha rang / purple color" },
  { id: 484, front: "経不住誘惑", back: "ゆうわくにまける — vasvasaga yengilmoq / to succumb to temptation" },
  { id: 485, front: "絡み合い", back: "からみあい — o'zaro bog'lanish, chalkashish / entanglement, intertwining" },
  { id: 486, front: "捻る", back: "ひねる — burmoq, aylantirmoq / to twist" },
  { id: 487, front: "総選挙", back: "そうせんきょ — umumiy saylov / general election" },
  { id: 488, front: "編み物", back: "あみもの — trikotaj, to'qish / knitting" },
  { id: 489, front: "編む", back: "あむ — to'qimoq / to knit" },
  { id: 490, front: "編集", back: "へんしゅう — tahrirlash / editing" },
  { id: 491, front: "漫画", back: "まんが — komiks / manga, comic" },
  { id: 492, front: "義務", back: "ぎむ — burch, majburiyat / duty, obligation" },
  { id: 493, front: "義理", back: "ぎり — majburiyat, qarz burchi / social obligation, duty" },
  { id: 494, front: "聞いたところ", back: "きいたところ — eshitishimcha / from what I heard" },
  { id: 495, front: "肌", back: "はだ — teri / skin" },
  { id: 496, front: "自然", back: "しぜん — oddiy, tabiiy / natural, simple" },
  { id: 497, front: "胃に管を通す", back: "いにかんをとおす — oshqozonga naycha o'tkazmoq / to pass a tube into the stomach" },
  { id: 498, front: "理解できない", back: "りかいできない — tushunib bo'lmaydi / cannot understand" },
  { id: 499, front: "宿題", back: "しゅくだい — uy vazifasi / homework" },
  { id: 500, front: "その頃", back: "そのころ — o'sha vaqt atrofida / around that time" },
  { id: 501, front: "自分の体型", back: "じぶんのたいけい — o'z tana shakli / one's own body shape" },
  { id: 502, front: "自宅", back: "じたく — o'z uyi, xususiy turar joy / one's own home, private residence" },
  { id: 503, front: "自然", back: "しぜん — tabiat / nature" },
  { id: 504, front: "自負", back: "じふ — g'urur, o'ziga ishonch / pride, self-confidence" },
  { id: 505, front: "努力", back: "どりょく — kuch-g'ayrat, harakat / effort" },
  { id: 506, front: "舞う", back: "まう — raqsga tushmoq, aylanmoq / to dance, flutter" },
  { id: 507, front: "舞台に出る", back: "ぶたいにでる — sahnaga chiqmoq / to go on stage" },
  { id: 508, front: "舞台で踊る", back: "ぶたいでおどる — sahnada raqsga tushmoq / to dance on stage" },
  { id: 509, front: "舞台衣装を着る", back: "ぶたいいしょうをきる — sahna liboslarini kiymoq / to wear stage costumes" },
  { id: 510, front: "舞食", back: "まいしょく — bayram taomi, marosim taomi / ceremonial meal" },
  { id: 511, front: "良い", back: "いい — yaxshi / good" },
  { id: 512, front: "良いところ", back: "よいところ — yaxshi tomonlari / good points" },
  { id: 513, front: "良き", back: "よき — yaxshi / good" },
  { id: 514, front: "良好", back: "りょうこう — yaxshi holat / good, favorable" },
  { id: 515, front: "良質", back: "りょうしつ — yaxshi sifat / good quality" },
  { id: 516, front: "色々考えた結果", back: "いろいろかんがえたけっか — turli fikrlar natijasida / as a result of much thought" },
  { id: 517, front: "小説的生活", back: "しょうせつてきせいかつ — romanga o'xshash hayot / novel-like life" },
  { id: 518, front: "花束", back: "はなたば — gulchambar / bouquet of flowers" },
  { id: 519, front: "若い頃", back: "わかいころ — yoshligida / when young" },
  { id: 520, front: "荒らす", back: "あらす — vayron qilmoq / to vandalize, ravage" },
  { id: 521, front: "荒れた肌がすべすべ", back: "あれたはだがすべすべ — qo'pol terini tekislaydi / smoothes rough skin" },
  { id: 522, front: "荒れた駅がすべすべ", back: "あれたえきがすべすべ — jimjimador vokzal silliq / the worn-down station made smooth" },
  { id: 523, front: "荒れる", back: "あれる — qo'pol bo'lmoq, buzilmoq / to become rough, turn wild" },
  { id: 524, front: "落ち着く", back: "おちつく — tinchlanmoq, joylashmoq / to calm down, settle" },
  { id: 525, front: "蒸し暑い", back: "むしあつい — dim va issiq / hot and humid" },
  { id: 526, front: "蒸し", back: "むし — bug'lash / steaming" },
  { id: 527, front: "柔らかい", back: "やわらかい — yumshoq / soft" },
  { id: 528, front: "薬も効かない", back: "くすりもきかない — dori ham ta'sir qilmaydi / medicine doesn't even work" },
  { id: 529, front: "薬を飲む", back: "くすりをのむ — dori ichmoq / to take medicine" },
  { id: 530, front: "薬草", back: "やくそう — dorivor o'simlik / medicinal herb" },
  { id: 531, front: "行かずに済む", back: "いかずにすむ — bormasdan bo'ladigan bo'lish / to not need to go" },
  { id: 532, front: "行く", back: "いく — bormoq / to go" },
  { id: 533, front: "行くくらい", back: "いくくらい — borish darajasida / to the extent of going" },
  { id: 534, front: "行けない", back: "いけない — bora olmaydi / cannot go" },
  { id: 535, front: "行う", back: "おこなう — bajarmoq, o'tkazmoq / to carry out, conduct" },
  { id: 536, front: "行ったかい", back: "いったかい — bordingmi? / did you go?" },
  { id: 537, front: "行って", back: "いって — borib / go and (te-form)" },
  { id: 538, front: "表のすぐそば", back: "おもてのすぐそば — old tomonning yonida / right next to the front" },
  { id: 539, front: "参照", back: "さんしょう — havola, murojaat / reference" },
  { id: 540, front: "驚愕", back: "きょうがく — dahshatga tushish / shock, astonishment" },
  { id: 541, front: "事故が起こった時", back: "じこがおこったとき — voqea sodir bo'lgan payt / when an accident occurred" },
  { id: 542, front: "製造", back: "せいぞう — ishlab chiqarish / manufacturing" },
  { id: 543, front: "製品", back: "せいひん — mahsulot / product" },
  { id: 544, front: "要する", back: "よう・する — talab qilmoq / to require, to take (time)" },
  { id: 545, front: "見るなり", back: "みるなり — ko'rishi bilanoq / as soon as seeing" },
  { id: 546, front: "見る", back: "みる — ko'rmoq / to see" },
  { id: 547, front: "見るなり", back: "みるなり — ko'rishi bilanoq / as soon as seeing" },
  { id: 548, front: "見舞い", back: "みまい — bemorni ko'rgani borish / get-well visit" },
  { id: 549, front: "見舞う", back: "みま・う — bemorni ko'rgani bormoq / to visit (someone ill)" },
  { id: 550, front: "言える", back: "い・える — aytish mumkin / can say" },
  { id: 551, front: "言える", back: "い・える — aytish mumkin / can say" },
  { id: 552, front: "言われる", back: "い・われる — aytilmoq / to be told" },
  { id: 553, front: "言われる", back: "い・われる — aytilmoq / to be told" },
  { id: 554, front: "言葉に恥をかけば", back: "ことばにはじをかけば — so'zlaringizdan uyalsangiz / if you shame yourself with words" },
  { id: 555, front: "計画", back: "けいかく — reja / plan" },
  { id: 556, front: "訳がありません", back: "わけがありません — hech qanday sabab yo'q / there's no reason" },
  { id: 557, front: "誘惑に負ける", back: "ゆうわくにまける — vasvasaga berilmoq / to succumb to temptation" },
  { id: 558, front: "試験", back: "しけん — imtihon / exam" },
  { id: 559, front: "詰まっている", back: "つまっている — tiqilib qolgan / clogged" },
  { id: 560, front: "話がある", back: "はなしがある — aytadigan gapim bor / there's something to talk about" },
  { id: 561, front: "話がつく", back: "はなしがつく — kelishuvga erishmoq / to come to an agreement" },
  { id: 562, front: "話がわからない", back: "はなしがわからない — gapni tushunmayapman / don't understand the point" },
  { id: 563, front: "話がわかる", back: "はなしがわかる — gapni tushunmoq / to understand the point" },
  { id: 564, front: "話が事実だとすれば", back: "はなしがじじつだとすれば — agar voqea rost bo'lsa / if the story is true" },
  { id: 565, front: "話にならない", back: "はなしにならない — gap bo'lishi mumkin emas / out of the question" },
  { id: 566, front: "話に乗る", back: "はなしにのる — taklifga qo'shilmoq / to go along with a proposal" },
  { id: 567, front: "話に乗る", back: "はなしにのる — suhbatga qo'shilmoq / to go along with a proposal" },
  { id: 568, front: "課程", back: "かてい — kurs / course (of study)" },
  { id: 569, front: "講義", back: "こうぎ — ma'ruza / lecture" },
  { id: 570, front: "講義", back: "こうぎ — ma'ruza / lecture" },
  { id: 571, front: "貝柱が高ければ", back: "かいばしらがたかければ — narx yuqori bo'lsa / if the price is high" },
  { id: 572, front: "負けてしまう", back: "まけてしまう — yutqazib qo'ymoq / to end up losing" },
  { id: 573, front: "財布を忘れた", back: "さいふをわすれた — hamyonini unutdi / forgot the wallet" },
  { id: 574, front: "財産の相続", back: "ざいさんのそうぞく — mulk merosi / inheritance of property" },
  { id: 575, front: "買い", back: "かい — sotib olish / buying" },
  { id: 576, front: "買いに行く", back: "かいにいく — sotib olgani bormoq / to go and buy" },
  { id: 577, front: "買い手のやること", back: "かいてのやること — xaridorning ishi / what the buyer does" },
  { id: 578, front: "買い換える", back: "かいかえる — yangisiga almashtirib sotib olmoq / to buy a replacement" },
  { id: 579, front: "買う", back: "か・う — sotib olmoq / to buy" },
  { id: 580, front: "買ってくる", back: "かってくる — sotib kelmoq / to go buy and bring back" },
  { id: 581, front: "頼み", back: "たのみ — iltimos / request, favor" },
  { id: 582, front: "頼む", back: "たの・む — iltimos qilmoq / to ask, to request" },
  { id: 583, front: "貸したらしい", back: "かしたらしい — qarzga berganga o'xshaydi / it seems (someone) lent it" },
  { id: 584, front: "資料は港へ", back: "しりょうはみなとへ — materiallar portga / materials to the port" },
  { id: 585, front: "資料は郵送する", back: "しりょうはゆうそうする — materiallar pochta orqali yuboriladi / materials will be sent by mail" },
  { id: 586, front: "質", back: "しつ — sifat / quality" },
  { id: 587, front: "贈品", back: "ぞうひん — sovg'a / gift item" },
  { id: 588, front: "赤ん坊", back: "あかんぼう — chaqaloq / baby" },
  { id: 589, front: "赤ん坊たち", back: "あかんぼうたち — chaqaloqlar / babies" },
  { id: 590, front: "赤ん坊", back: "あかんぼう — chaqaloq / baby" },
  { id: 591, front: "足または姉", back: "あしまたはあね — oyoq yoki opa / leg or older sister" },
  { id: 592, front: "足球", back: "サッカー — futbol / football (soccer)" },
  { id: 593, front: "転居する", back: "てんきょする — ko'chib o'tmoq / to relocate" },
  { id: 594, front: "辛口", back: "からくち — achchiq/quruq ta'm / dry, spicy taste" },
  { id: 595, front: "辞めたい", back: "やめたい — ish tashlamoqchi / want to quit" },
  { id: 596, front: "返還しません", back: "へんかんしません — qaytarilmaydi / will not be returned" },
  { id: 597, front: "途中から雨", back: "とちゅうからあめ — yo'l-yo'lakay yomg'ir yog'a boshladi / it started raining halfway" },
  { id: 598, front: "連絡してください", back: "れんらくしてください — bog'laning / please contact me" },
  { id: 599, front: "週間", back: "しゅうかん — hafta / week" },
  { id: 600, front: "行く", back: "い・く — bormoq / to go" },
  { id: 601, front: "遊んでいる", back: "あそんでいる — o'ynamoqda / playing" },
  { id: 602, front: "過ごした", back: "すご・した — o'tkazdi (vaqt) / spent (time)" },
  { id: 603, front: "過程", back: "かてい — jarayon / process" },
  { id: 604, front: "過程を表したもの", back: "かていをあらわしたもの — jarayonni ifodalovchi narsa / something that represents a process" },
  { id: 605, front: "道具", back: "どうぐ — asbob / tool" },
  { id: 606, front: "達成感が増す", back: "たっせいかんがます — muvaffaqiyat tuyg'usi kuchayadi / sense of accomplishment increases" },
  { id: 607, front: "違い", back: "ちがい — farq / difference" },
  { id: 608, front: "選ぶ", back: "えら・ぶ — tanlamoq / to choose" },
  { id: 609, front: "選手", back: "せんしゅ — sportchi / athlete, player" },
  { id: 610, front: "部品", back: "ぶひん — qismlar / parts" },
  { id: 611, front: "配達者", back: "はいたつしゃ — yetkazib beruvchi / delivery person" },
  { id: 612, front: "酒ができた", back: "さけができた — sake tayyor bo'ldi / the sake is ready" },
  { id: 613, front: "酒をやめる", back: "さけをやめる — ichkilikni tashlamoq / to quit drinking alcohol" },
  { id: 614, front: "醤油", back: "しょうゆ — soya sousi / soy sauce" },
  { id: 615, front: "邪魔する", back: "じゃまする — xalaqit bermoq / to disturb, to get in the way" },
  { id: 616, front: "金", back: "きん — oltin / gold" },
  { id: 617, front: "金の気持ちに関し", back: "かねのきもちにかんし — pulga bo'lgan his-tuyg'ular haqida / regarding feelings about money" },
  { id: 618, front: "母が亡くなった", back: "ははがなくなった — onasi vafot etdi / (his/her) mother passed away" },
  { id: 619, front: "鈍い", back: "にぶ・い — o'tmas, sust / dull, slow" },
  { id: 620, front: "鈍感", back: "どんかん — befarqlik, sezgirlik yo'qligi / insensitivity" },
  { id: 621, front: "鈍感だ", back: "どんかんだ — befarq / insensitive" },
  { id: 622, front: "敏感", back: "びんかん — sezgirlik / sensitivity" },
  { id: 623, front: "鋭い", back: "するど・い — keskin, o'tkir / sharp" },
  { id: 624, front: "鋭い", back: "するど・い — o'tkir / sharp" },
  { id: 625, front: "敏感", back: "びんかん — keskin sezgirlik / keen sense, sensitivity" },
  { id: 626, front: "錯誤", back: "さくご — xatolik / error, mistake" },
  { id: 627, front: "長い", back: "なが・い — uzun / long" },
  { id: 628, front: "長編と短編", back: "ちょうへんとたんぺん — uzun hikoya va qisqa hikoya / novel and short story" },
  { id: 629, front: "間に合いかねる", back: "まにあいかねる — vaqtida ulgurish qiyin / unable to make it in time" },
  { id: 630, front: "間に合いがたい", back: "まにあいがたい — vaqtida ulgurish qiyin / hard to make it in time" },
  { id: 631, front: "間に合う", back: "まにあう — vaqtida bo'lmoq / to be in time" },
  { id: 632, front: "間に合う", back: "まにあう — vaqtida bo'lmoq / to be in time" },
  { id: 633, front: "関する", back: "かんする — tegishli bo'lmoq / to relate to" },
  { id: 634, front: "降る", back: "ふる — (yomg'ir, qor) yog'moq / to fall (rain, snow)" },
  { id: 635, front: "集める", back: "あつめる — to'plamoq, yig'moq / to collect, gather" },
  { id: 636, front: "雨が降る", back: "あめがふる — yomg'ir yog'moq / rain falls" },
  { id: 637, front: "雨季", back: "うき — yomg'irli mavsum / rainy season" },
  { id: 638, front: "雲が広がる", back: "くもがひろがる — bulutlar yoyilmoq / clouds spread" },
  { id: 639, front: "電気", back: "でんき — elektr / electricity" },
  { id: 640, front: "電子", back: "でんし — elektron / electronic" },
  { id: 641, front: "電話", back: "でんわ — telefon / telephone" },
  { id: 642, front: "霧", back: "きり — tuman / fog, mist" },
  { id: 643, front: "青島", back: "あおしま — Aoshima (joy nomi) / Aoshima (place name)" },
  { id: 644, front: "順序", back: "じゅんじょ — tartib / order, sequence" },
  { id: 645, front: "順番", back: "じゅんばん — navbat / turn, order" },
  { id: 646, front: "頭が痛い", back: "あたまがいたい — boshim og'riydi / my head hurts" },
  { id: 647, front: "頭痛がやむ", back: "ずつうがやむ — bosh og'rig'i to'xtaydi / headache stops" },
  { id: 648, front: "頭痛", back: "ずつう — bosh og'rig'i / headache" },
  { id: 649, front: "頭を上げる", back: "あたまをあげる — boshni ko'tarmoq / to raise one's head" },
  { id: 650, front: "頭痛がひどい", back: "ずつうがひどい — dahshatli bosh og'rig'i bor / to have a terrible headache" },
  { id: 651, front: "頭脳を持つ", back: "ずのうをもつ — miyaga ega bo'lmoq / to have a brain" },
  { id: 652, front: "贈り物", back: "おくりもの — sovg'a / gift" },
  { id: 653, front: "食に対して", back: "しょくにたいして — oziq-ovqatga nisbatan / with regard to food" },
  { id: 654, front: "食べっぷり", back: "たべっぷり — ovqatlanish tarzi / manner of eating" },
  { id: 655, front: "食をけなす", back: "しょくをけなす — taomni yomonlamoq / to disparage food" },
  { id: 656, front: "食事する", back: "しょくじする — ovqatlanmoq / to have a meal" },
  { id: 657, front: "食欲", back: "しょくよく — ishtaha / appetite" },
  { id: 658, front: "看護師", back: "かんごし — hamshira / nurse" },
  { id: 659, front: "首", back: "くび — bo'yin / neck" },
  { id: 660, front: "駅に着く", back: "えきにつく — stansiyaga yetib kelmoq / to arrive at the station" },
  { id: 661, front: "高い", back: "たかい — qimmat, baland / expensive, tall/high" },
  { id: 662, front: "お金をかける", back: "おかねをかける — pul sarflamoq / to spend money" },
  { id: 663, front: "高価", back: "こうか — qimmat baho / high price, expensive" },
  { id: 664, front: "寒くなる", back: "さむくなる — sovuq bo'lib qolmoq / to become cold" },
  { id: 665, front: "鬱", back: "うつ — depressiya / depression" },
  { id: 666, front: "魚", back: "さかな — baliq / fish" },
  { id: 667, front: "魚といい形といい", back: "さかなといいかたちといい — baliq ham, shakli ham yaxshi / both the fish and the shape are good" },
  { id: 668, front: "鳴子", back: "なるこ — Naruko (joy nomi/asbob) / Naruko (place name/noisemaker device)" },
  { id: 669, front: "黒い", back: "くろい — qora / black" },
  { id: 670, front: "黒くなる", back: "くろくなる — qora rangga aylanmoq / to turn black" },
  { id: 671, front: "黒で行く", back: "くろでいく — qora rangni tanlamoq / to go with black" },
  { id: 672, front: "黒い手の動き", back: "くろいてのうごき — qorong'u qo'l harakati / dark/shady hand movement" },
  { id: 673, front: "黒金", back: "くろがね — temir (eski so'z) / iron (archaic term)" },
];

export const deckGroups: DeckGroup[] = [
  {
    id: "Set-1",
    title: "Vocabulary 1-673",
    level: "JLPT N3/N2",
    startIndex: 1,
    endIndex: 673,
    cardCount: 673
  }
];

export function getCardsForGroup(groupId: string): Card[] {
  const group = deckGroups.find(g => g.id === groupId);
  if (!group) return [];
  
  return flashcards.filter(c => c.id >= group.startIndex && c.id <= group.endIndex);
}
